<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ko" xml:lang="ko"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.34">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>10&nbsp; 다변량 분산분석 – 다변량통계학-2025년 2학기</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../references.html" rel="next">
<link href="../qmd/multivar-cluster.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-c8ad9e5dbd60b7b70b38521ab19b7da4.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-d3c9390091c69a50683db05bc45f20d8.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "일치 없음",
    "search-matching-documents-text": "일치된 문서",
    "search-copy-link-title": "검색 링크 복사",
    "search-hide-matches-text": "추가 검색 결과 숨기기",
    "search-more-match-text": "추가 검색결과",
    "search-more-matches-text": "추가 검색결과",
    "search-clear-button-title": "제거",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "취소",
    "search-submit-button-title": "검색",
    "search-label": "검색"
  }
}</script>
<script type="text/javascript">
 window.MathJax = {
  tex: {
    macros: {
    RR: '{\\mathbb R}',                    // a simple string replacement
    hatmat:'{\\pmb X ({\\pmb X}^t {\\pmb X} )^{-1} {\\pmb X}^t}',
    bold: ['\\boldsymbol{#1}',1] ,     // this macro has one parameter
    pardiff: ['\\frac{\\partial#2}{\\partial#1}', 2, 'x'], // this macro has an optional parameter that defaults to 'x'
    pardifftwo: ['\\frac{\\partial#1}{\\partial#2}', 2],
    pardiffd: ['\\frac{\\partial#1}{\\partial#2^t \\partial#2}', 2],
    pardiffdd: ['\\frac{\\partial#1}{\\partial#3 \\partial#2}', 3],
    norm: ['\\lVert#1\\rVert',1]
  },
  environments: {
  braced: ["\\left\\{", "\\right\\}"]
  }
 }
};
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="사이드바 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../qmd/multivar-anova.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">다변량 분산분석</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="사이드바 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="검색" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">다변량통계학-2025년 2학기</a> 
        <div class="sidebar-tools-main">
    <a href="../다변량통계학-2025년-2학기.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="검색"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/multivar-dist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">확률벡터와 다변량 정규분포</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/multivar-vis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">다변량 자료의 시각화</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/multivar-test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">다변량 가설 검정</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/multivar-cov.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">공분산 행렬의 추정</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/multivar-discrim.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">판별분석</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/multivar-pca.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">주성분 분석</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/multivar-cancor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">정준상관분석</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/multivar-factor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">탐색적 인자 분석</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/multivar-cluster.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">군집 분석</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/multivar-anova.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">다변량 분산분석</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/math_mat_basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">행렬의 기초</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/math_eigen_value.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">고유값과 고유벡터</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/math_matrix_decomp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">행렬의 분해</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/app-likelihood-ratio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">가능도비 검정</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">목차</h2>
   
  <ul>
  <li><a href="#sec-repeatmeasure-paired" id="toc-sec-repeatmeasure-paired" class="nav-link active" data-scroll-target="#sec-repeatmeasure-paired"><span class="header-section-number">10.1</span> 독립표본과 쌍표본</a></li>
  <li><a href="#repeatmeasure-oneway" id="toc-repeatmeasure-oneway" class="nav-link" data-scroll-target="#repeatmeasure-oneway"><span class="header-section-number">10.2</span> 일원배치 모형</a>
  <ul class="collapse">
  <li><a href="#고정효과-모형" id="toc-고정효과-모형" class="nav-link" data-scroll-target="#고정효과-모형"><span class="header-section-number">10.2.1</span> 고정효과 모형</a></li>
  <li><a href="#혼합효과-모형" id="toc-혼합효과-모형" class="nav-link" data-scroll-target="#혼합효과-모형"><span class="header-section-number">10.2.2</span> 혼합효과 모형</a></li>
  </ul></li>
  <li><a href="#반복측정자료" id="toc-반복측정자료" class="nav-link" data-scroll-target="#반복측정자료"><span class="header-section-number">10.3</span> 반복측정자료</a>
  <ul class="collapse">
  <li><a href="#개체들의-선형-회귀모형" id="toc-개체들의-선형-회귀모형" class="nav-link" data-scroll-target="#개체들의-선형-회귀모형"><span class="header-section-number">10.3.1</span> 개체들의 선형 회귀모형</a></li>
  <li><a href="#sec-randomcoef" id="toc-sec-randomcoef" class="nav-link" data-scroll-target="#sec-randomcoef"><span class="header-section-number">10.3.2</span> 임의계수 모형</a></li>
  </ul></li>
  <li><a href="#최대가능도-추정" id="toc-최대가능도-추정" class="nav-link" data-scroll-target="#최대가능도-추정"><span class="header-section-number">10.4</span> 최대가능도 추정</a>
  <ul class="collapse">
  <li><a href="#선형회귀모형" id="toc-선형회귀모형" class="nav-link" data-scroll-target="#선형회귀모형"><span class="header-section-number">10.4.1</span> 선형회귀모형</a></li>
  <li><a href="#최대가능도-추정-1" id="toc-최대가능도-추정-1" class="nav-link" data-scroll-target="#최대가능도-추정-1"><span class="header-section-number">10.4.2</span> 최대가능도 추정</a></li>
  <li><a href="#선형혼합효과모형의-구조" id="toc-선형혼합효과모형의-구조" class="nav-link" data-scroll-target="#선형혼합효과모형의-구조"><span class="header-section-number">10.4.3</span> 선형혼합효과모형의 구조</a></li>
  <li><a href="#선형혼합모형의-분포" id="toc-선형혼합모형의-분포" class="nav-link" data-scroll-target="#선형혼합모형의-분포"><span class="header-section-number">10.4.4</span> 선형혼합모형의 분포</a></li>
  <li><a href="#최대가능도-추정법" id="toc-최대가능도-추정법" class="nav-link" data-scroll-target="#최대가능도-추정법"><span class="header-section-number">10.4.5</span> 최대가능도 추정법</a></li>
  </ul></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content column-page-right" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-repeatmeasure" class="quarto-section-identifier"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">다변량 분산분석</span></span></h1>
</div>



<div class="quarto-title-meta column-page-right">

    
  
    
  </div>
  


</header>


<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmerTest)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co">#아래 3 문장은 한글을 포함한 ggplot 그림이 포함된 HTML, PDF로 만드는 경우 사용</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(showtext)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co">#font_add_google("Nanum Pen Script", "gl")</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">font_add_google</span>(<span class="at">name =</span> <span class="st">"Noto Sans KR"</span>, <span class="at">family =</span> <span class="st">"noto"</span>)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">showtext_auto</span>()</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="sec-repeatmeasure-paired" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="sec-repeatmeasure-paired"><span class="header-section-number">10.1</span> 독립표본과 쌍표본</h2>
<p>서로 다른 두 처리의 효과(treatment effect)를 비교하기 위하여 주로 사용되는 방법은 두 개의 독립표본(independent sample)을 비교하는 t-검정법이다. 서로 독립인 두개의 집단(구성원이 겹치지 않는 집단)에 서로 다른 처리를 적용한 뒤에 관측된 자료의 표본 평균을 비교하여 두 개의 처리 효과의 차이를 통계적으로 검정하는 방법이다. t-검정을 위한 분포 가정은 다음과 같다.</p>
<p><span class="math display">\[
x_1,x_2, \dots x_{n} \sim_{iid} N(\mu_1, \sigma^2)
\quad
y_1,y_2, \dots y_{n} \sim_{iid} N(\mu_2, \sigma^2)
\]</span></p>
<p>위의 가정을 다음과 같은 평균모형(mean model)로 표현할 수 있다.</p>
<p><span id="eq-re-meanmodel"><span class="math display">\[
x_i = \mu_1 + e_{i1}, \quad y_i = \mu_2 + e_{i2}  
\tag{10.1}\]</span></span></p>
<p>여기서 <span class="math inline">\(e_{i1}\)</span>와 <span class="math inline">\(e_{i2}\)</span>들은 모두 독립이며 <span class="math inline">\(N(0,\sigma^2)\)</span>을 따르는 오차들이다.</p>
<p>여기서 확률변수 <span class="math inline">\(x\)</span>와 <span class="math inline">\(y\)</span>는 서로 독립이고 각 관측값 <span class="math inline">\(x_1,x_2, \dots x_{n_1}\)</span>과 <span class="math inline">\(y_1,y_2, \dots y_{n_2}\)</span>들도 각각 모두 독립이다. 분포가정에서 다른 것은 확률변수 <span class="math inline">\(x\)</span>와 <span class="math inline">\(y\)</span>의 평균이 다르다.</p>
<p>이러한 가정 하에서 다음의 두개의 가설검정을 할 수 있는 방법이 t-검정법이며</p>
<p><span id="eq-re-hypo"><span class="math display">\[
H_0 : \mu_1 = \mu_2 \quad \text{vesus} \quad H_1 : \mu_1 \ne \mu_2  
\tag{10.2}\]</span></span></p>
<p>검정통계량은 다음과 같이 주어진다.</p>
<p><span id="eq-re-tvalue1"><span class="math display">\[
t = \frac{ \bar x -\bar y} {s_p \sqrt{\tfrac{1}{n} + \tfrac{1}{n}}}  
\tag{10.3}\]</span></span></p>
<p>여기서 <span class="math inline">\(\bar x\)</span>와 <span class="math inline">\(\bar y\)</span>는 각 집단의 표본 평균이고 <span class="math inline">\(s_p^2\)</span>은 합동분산추정량(pooled variance estimator)이다.</p>
<p><span class="math display">\[ s^2_p = \frac{\sum_{i=1}^n (x_i -\bar x)^2 + \sum_{i=1}^n (y_i -\bar y)^2 }{2n-2} \]</span></p>
<p>이제 두 개의 처리를 비교하는 경우, 독립 표본이 아닌 경우를 고려해 보자.</p>
<p>독립 표본이 아닌 대표적인 경우가 쌍표본(또는 대응표본)에 대한 t-검정이다(paired t-test). 쌍표본 검정에서는 하나의 개체에 두 개의 처리를 모두 적용하여 각 처리에 대한 반응값을 쌍 <span class="math inline">\((x_i,y_i)\)</span>으로 얻는다. 예를 들어 최초로 허가 받은 약품과 복제약의 생물학적동등성(bioequivalence)을 입증하는 실험에서는 한 사람에게 최초허가약을 투여하여 약의 효과를 보고 일정 시간이 지난 뒤 복제약을 같은 사람에게 투여하여 그 효과를 측정한다. 다른 예로서 두 개의 눈병 치료제를 각각 누에 투여하여 효과를 비교하는 경우도 이러한 쌍표본에 속한다. 넓은 의미에서 일란성 쌍둥이에게 각각 다른 처리를 하여 비교하는 것도 대응비교라고 할 수 있다.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../images/design22.jpg" class="img-fluid figure-img"></p>
<figcaption>생물학적동등성 실험에서 사용되는 교차실험(crossover design) - 개체 당 2개의 관측치 (각 처리에 대하여 한 개의 관측값)</figcaption>
</figure>
</div>
<p>가장 단순한 대응비교로서 각 개체애 대하여 두 개의 처리에 대한 쌍표본 <span class="math inline">\((x_i,y_i)\)</span>를 관측한다고 가정하자. 이에 대한 분포 모형은 다음과 같다.</p>
<p><span class="math display">\[
d_i = x_i -y_i  \sim_{iid} N(\delta,\sigma^2) \text { where } \delta = \mu_1-\mu_2 = E(x)-E(y)
\]</span></p>
<p>대응비교에서 사용되는 t-통계량은 다음과 같다.</p>
<p><span id="eq-re-tvalue2"><span class="math display">\[
t = \frac{ \bar d} {s_d / \sqrt{n}} =\frac{ \bar x -\bar y} {s_d / \sqrt{n}}  
\tag{10.4}\]</span></span></p>
<p>여기서 <span class="math inline">\(s^2_d\)</span>는 <span class="math inline">\(d_1,d_2,\dots ,d_n\)</span>의 표본분산이다.</p>
<p><span class="math display">\[ s^2_d = \frac{\sum_{i=1}^n (d_i -\bar d)^2}{n-1} \]</span></p>
<p>위에서 알아본 독립표본에 의한 비교와 쌍표본에 의한 비교가 다른 점은 무었일까 생각해 보자. 표본의 비교가 다른 개체에서 추출된 독립인 관측치를 이용하는지 또는 같은 개체에서 추출된 대응하는(독립이 아닌) 관측치를 이용하는지에 따라서 서로 다른 t-통계량을 사용한다. 식 <a href="#eq-re-tvalue1" class="quarto-xref">식&nbsp;<span>10.3</span></a> 과 식 <a href="#eq-re-tvalue2" class="quarto-xref">식&nbsp;<span>10.4</span></a> 에 나타난 t-통계량을 비교하면 분자에 나타난 통계량은 효과의 차이를 나타내는 두 개의 평균의 차이로서 기본적으로 동일하다<span class="math inline">\((\bar d =\bar x -\bar y)\)</span>. 하지만 분모에서는 분자에 나타난 통계량의 표본오차(standard error)를 나타내는 양으로서 서로 다르다. 독립표본에서는 표본의 평균이 서로 독립이므로 다음과 같이 평균의 차이에 대한 분산이 각각의 분산의 합과 같으므로 이에 대한 추정량으로서 합동분산추정량을 이용하였다.</p>
<p><span id="eq-re-varsum"><span class="math display">\[
Var(\bar x - \bar y) = Var(\bar x) + Var(\bar y)  
\tag{10.5}\]</span></span><br>
쌍표본에서는 위의 식 <a href="#eq-re-varsum" class="quarto-xref">식&nbsp;<span>10.5</span></a> 을 적용할 수 없다. 왜냐하면 두개의 표본 평균이 서로 독립이 아닐 가능성이 매우 높기 때문이다. 같은 개체에서 나온 관측치는 어떠한 형태로든 서로 관계가 있을 가능성이 높기 때문에 독립을 함부로 가정할 수 없다. 예를 들어 생물학적동등성 실험에서는 약 효과의 차이보다 약이 몸에 흡수되는 개인적인 체질이 관측값에 더 큰 영향을 줄 수 있다.</p>
<p>확률변수 <span class="math inline">\(x\)</span>와 <span class="math inline">\(y\)</span>가 독립이 아닌 경우 두 모형균의 차이를 비교하기 위하여 비교에 사용된 통계양은 두 확률변수의 차이다. <span class="math display">\[ d_i = x_i - y_i \]</span> 여기서 두 개의 확률변수의 차이를 이용할 때 암시적인 가정은 두 개의 확률변수의 차이를 내면 두 변수에 공통적으로 포함된 개인의 특성이 서로 상쇄되어 처리의 차이만이 확률변수 <span class="math inline">\(d_i\)</span>에 존재한다는 것이다. 지금 설명한 대응비교 모형의 합리적인 가정을 요약하면 다음과 같다.</p>
<ul>
<li>개인의 특성을 반영하는 공통 요인이 두 변수에 모두 영향을 미친다.</li>
<li>따라서 두 관측값 <span class="math inline">\((x_i,y_i)\)</span>가 독립이 아니다</li>
<li>두 관측값의 차이를 내면 공통요인이 서로 상쇄되어 처리효과만 남는다.</li>
</ul>
<p><span class="math display">\[ E(d_i) = \mu_1 - \mu_2 \]</span></p>
<p>위의 가정을 구현할 수 있는 대응비교 모형을 다음과 같은 가법모형(additive models)로 표현할 수 있다.</p>
<p><span id="eq-re-paired"><span class="math display">\[  
x_i = \mu_1 + a_i + e_{i1}, \quad y_i = \mu_2 + a_i + e_{i2}
\tag{10.6}\]</span></span></p>
<p>여기서 <span class="math inline">\(a_i\)</span>는 두 확률변수 <span class="math inline">\((x_i,y_i)\)</span>에 공통으로 포함된 개인적인 특성을 나타내는 요인이며 위의 식 <a href="#eq-re-paired" class="quarto-xref">식&nbsp;<span>10.6</span></a> 는 식 <a href="#eq-re-meanmodel" class="quarto-xref">식&nbsp;<span>10.1</span></a> 에 공통요인 <span class="math inline">\(a_i\)</span>가 추가된 형태이다.</p>
<p>두 확률변수 <span class="math inline">\((x_i,y_i)\)</span>가 종속이기 위해서는 다음과 같은 가정을 이용할 수 있다.</p>
<p><span class="math display">\[ a_i \sim N(0, \sigma^2_a), \quad  e_{i1} \sim_{iid}  N(0, \sigma^2_e)  \quad e_{i2} \sim_{iid}  N(0, \sigma^2_e)   \]</span></p>
<p>여기서 <span class="math inline">\(a_i\)</span>가 평균이 0이고 분산이 <span class="math inline">\(\sigma_a^2\)</span> 인 확률변수이다. 이러한 요인을 임의효과(random effect)라고 하며 모수(parameter)인 평균 <span class="math inline">\(\mu_i\)</span>은 고정효과(fixed effect)라고 부른다. <span class="math inline">\(e_{i1}\)</span>와 <span class="math inline">\(e_{i2}\)</span>들은 모두 독립이며 평균이 <span class="math inline">\(0\)</span> 이고 분산이 <span class="math inline">\(\sigma^2_e\)</span>인 정규분포를 따르는 오차들이다. 또한 <span class="math inline">\(a_i\)</span>와 (<span class="math inline">\(e_{i1}\)</span>,<span class="math inline">\(e_{i2}\)</span>)도 독립이다.</p>
<p>위와 같은 가정에서 두 변수의 차이를 내면 공통요인인 <span class="math inline">\(a_i\)</span>가 제거되어 두 처리의 차이만이 남게되며 <span class="math inline">\(x_i\)</span>와 <span class="math inline">\(y_i\)</span>는 분포의 가정상 독립이 아니다.</p>
<p><span class="math display">\[
\begin{aligned}
d_i &amp; = x_i -y_i \\
   &amp; = \mu_1+ a_i + e_{i1} -(\mu_2+ a_i + e_{i2}) \\
   &amp; = \mu_1 -\mu_2 +(e_{i1}-e_{i2}) \\
   &amp; = \mu_1 -\mu_2 +e^*_i \\
Cov(x_i,y_i) &amp; = Cov(\mu_1+ a_i + e_{i1},\mu_2+ a_i + e_{i2}) \\
    &amp; =  Cov(a_i, a_i) \\
    &amp; =  Var(a_i) \\
    &amp; =  \sigma^2_a
\end{aligned}    
\]</span></p>
<p>다음 절에서는 여기서 논의한 독립표본과 쌍표본의 개념 및 추정법을 일반적인 선형모형으로 확장하여 체계적인 비교를 해볼것이다.</p>
</section>
<section id="repeatmeasure-oneway" class="level2" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="repeatmeasure-oneway"><span class="header-section-number">10.2</span> 일원배치 모형</h2>
<section id="고정효과-모형" class="level3" data-number="10.2.1">
<h3 data-number="10.2.1" class="anchored" data-anchor-id="고정효과-모형"><span class="header-section-number">10.2.1</span> 고정효과 모형</h3>
<p>먼저 일원배치 요인계획(one-way factor design)이용한 실험을 생각해 보자. 고려하는 요인의 수준의 개수를 <span class="math inline">\(I\)</span>라고 하면 <span class="math inline">\(I\)</span>개의 수준 중에 하나를 임의로 선택하여 실험대상에 적용하는 임의화 방법으로 각 수준마다 <span class="math inline">\(J\)</span>의 관측값을 얻어다고 하자. 다음과 같은 ANOVA모형을 고려하여 분석을 할 수 있다.</p>
<p><span id="eq-re-anova"><span class="math display">\[
y_{ij} = \mu + \alpha_i + e_{ij}, \quad i=1,2,\dots,I \text{ and } j=1,2,\dots, J
\tag{10.7}\]</span></span></p>
<p>여기서 <span class="math inline">\(e_{ij}\)</span>는 서로 독립이며 <span class="math inline">\(N(0,\sigma_e^2)\)</span>를 따르는 오차항이다.</p>
<p>ANOVA 모형 <a href="#eq-re-anova" class="quarto-xref">식&nbsp;<span>10.7</span></a> 에서 <span class="math inline">\(\mu\)</span>와 <span class="math inline">\(\alpha_i\)</span>는 고정효과(fixed effect)라고 부르며 추정해야 할 모수(parameter)이다. 세심하게 설계된 실험에서는 수준에 대한 효과 <span class="math inline">\(\alpha_i\)</span>의 값이 변하지 않게 통제할 수 있는 실험 환경이 가능하다고 생각할 수 있으므로 <span class="math inline">\(\alpha_i\)</span>의 값을 변하지 않는 고정효과로 보는 것이 합리적이다.</p>
<p>일원배치 요인계획을 이용한 실험에서는 주요 관심사가 수준간의 차이가 있는지에 대한 것이며 이는 제곱합을 이용한 ANOVA table에서 F-test를 이용하여 검정할 수 있다.</p>
<p><span class="math display">\[ H_0: \alpha_1 = \alpha_2 =\dots = \alpha_I \]</span></p>
</section>
<section id="혼합효과-모형" class="level3" data-number="10.2.2">
<h3 data-number="10.2.2" class="anchored" data-anchor-id="혼합효과-모형"><span class="header-section-number">10.2.2</span> 혼합효과 모형</h3>
<p>이제 다음과 같은 자료의 추출을 생각해 보자. 서울시 A구에 초등학교가 20개있다고 하자. 20개의 학교중 6개의 학교를을 임의로 추출하고 추출된 학교에 속한 모든 6학년 학생들에게 과학시험을 보게하여 점수를 얻었다. 이러한 자료에서 학생들의 성적은 모두 같지 않을 것이 당연하며 가장 점수가 낮은 학생부터 높은 학생까지 점수의 변동(variation)이 존재한다. 변동의 요인은 무었일까? 학생의 개인의 차이(예:학생의 지능, 노력 정도, 학습 환경)도 변동의 요인이지만 또한 학교의 차이도 변동의 요인이 될 수 있다.</p>
<p>여기서 학교에 대한 요인은 앞 절에서 본 실험 자료에서 나타나는 고정 효과에 의한 요인과는 성격이 틀리다. 20개의 학교라는 모집단에서 6개의 학교가 추출되었으며 이 때 학교의 차이는 설계된 실험에서는 수준에 대한 효과와는 다르게 표본 추출 때문에 생기는 변동이라고 할 수 있다. 또한 같은 학교에 다니는 학생들은 같은 지역과 교사 등 공통적인 요인에 의하여 영향을 받는다고 가정할 수 있다. 따라서 같은 학교에 다는 학생들의 성적이 독립이 아닐 수도 있다.</p>
<p>이러한 효과를 임의효과(random effect)라고 부르며 학생들의 과학점수에 대한 모형을 다음과 같은 혼합효과모형(mixed effects model)으로 설명할 수 있다.</p>
<p><span id="eq-re-onewayrandom"><span class="math display">\[
y_{ij} = \mu + a_i + e_{ij}, \quad i=1,2,\dots,I \text{ and } j=1,2,\dots, J  
\tag{10.8}\]</span></span></p>
<p>여기서 <span class="math inline">\(a_i\)</span>는 학교의 효과를 나타내는 임의효과이며 서로 독립이고 <span class="math inline">\(N(0,\sigma_a^2)\)</span>를 따른다. 또한 개인에 대한 효과 또는 오차항 <span class="math inline">\(e_{ij}\)</span>는 서로 독립이며 <span class="math inline">\(N(0,\sigma_e^2)\)</span>를 따른다. 임의효과 <span class="math inline">\(a_i\)</span>와 오차항 <span class="math inline">\(e_{ij}\)</span>는 서로 독립이다. 고정효과 <span class="math inline">\(\mu\)</span>는 전체 평균을 나타내는 모수이다. 학교를 추출할 때 그 효과를 분산이 <span class="math inline">\(\sigma^2_a\)</span>를 가지는 정규모집단에서 추출한다고 가정하는 것이다. 학교를 하나의 군집(cluster)로 생각하고 학교의 효과를 군집효과로 보고 총변동을 설명하고 나머지 변동은 오차의 변동으로 개인의 효과 등으로 설명한다.</p>
<p><span class="math display">\[ Var(y_{ij}) =Var(\mu + a_i + e_{ij}) = Var(a_i) + Var(e_{ij}) = \sigma^2_a + \sigma^2_e \]</span></p>
<p>식 <a href="#eq-re-onewayrandom" class="quarto-xref">식&nbsp;<span>10.8</span></a> 로 표현된 임의효과를 포함한 혼합모형(일원배치 임의효과 모형; one-way random effect models)의 가장 큰 특징 중에 하나는 같은 군집에 속하는 관측치들은 서로 독립이 아니며 양의 상관관계가 있다. 위의 예제에서 두 학생 <span class="math inline">\(j\)</span>와 <span class="math inline">\(k\)</span>가 같은 학교 <span class="math inline">\(i\)</span>에 속한다면</p>
<p><span class="math display">\[ Cov(y_{ij},y_{ik}) = Cov(  \mu + a_i + e_{ij}, \mu + a_i + e_{ik}) =Cov (a_i, a_i)=\sigma^2_a \]</span> 따라서</p>
<p><span class="math display">\[ corr(y_{ij},y_{ik})= \frac{ Cov(y_{ij},y_{ik})}{\sqrt{Var(y_{ij})Var(y_{ik})} } = \frac{\sigma^2_a }{\sigma^2_a + \sigma^2_e } \]</span></p>
<p>위의 상관계수를 보면 학교간의 변동의 크기를 나타내는 <span class="math inline">\(\sigma^2_a\)</span>각 개인간의 변동을 나타내는 <span class="math inline">\(\sigma^2_e\)</span>보다 상대적으로 클수록 상관계수가 1에 가까와진다. 보통 <span class="math inline">\(\sigma^2_a\)</span>을 집단간 변동(between-group variance)라 하고 <span class="math inline">\(\sigma^2_e\)</span>를 집단내 변동(within-group variance)라고 한다. 따라서 <span class="math inline">\(\sigma^2_a\)</span>와 <span class="math inline">\(\sigma^2_e\)</span>의 상대적인 크기의 차이에 따라 군집내 관측값의 상관관계가 달라진다.</p>
<p>식 <a href="#eq-re-onewayrandom" class="quarto-xref">식&nbsp;<span>10.8</span></a> 의 임의효과 모형은 임의효과가 2개 이상인 모형으로 학장될 수 있다. 예제에서 학교를 추출하고 학교내에서 학급을 추출하여 추출된 학급내의 학생들이 시험을 보면 다음과 같은 모형을 적용할 수 있다.</p>
<p><span class="math display">\[
y_{ijk} = \mu + a_i + b_{ij} + e_{ijk}
\]</span></p>
<p>위의 모형에서 <span class="math inline">\(a_i\)</span>는 <span class="math inline">\(N(0,\sigma^2_a)\)</span>를 따르는 학교에 대한 임의효과, <span class="math inline">\(b_{ij}\)</span>는 <span class="math inline">\(N(0,\sigma^2_b)\)</span>를 따르는 학급에 대한 임의효과, <span class="math inline">\(e_{ijk}\)</span>는 <span class="math inline">\(N(0,\sigma^2_e)\)</span>를 따르는 학생에 대한 임의효과 또는 오차항으로 생각할 수 있다.</p>
<p>임의효과 모형에 고정효과가 같이 포함되어 있는 모형을 혼합모형(mixed model)이라고 부르며 반응변수의 변동에 영향을 미치는 요인들 또는 예측변수 중에서 임의효과와 고정효과를 구별하여 정하고 동시에 모형에 포함시킬수 있다. 예를 들어서 학교를 선택하여 과학시험을 볼 경우에 학기가 시작할 떄 과학교수법 두가지 중 하나를 임의화해서 각 학교에 배정하여 배정된 교수법으로 학생을 가르친 후에 시험을 보았다면 교수법에 대한 효과는 고정효과로 볼 수 있다. 따라서 다음과 같은 모형을 고려할 수 있다.</p>
<p><span id="eq-re-compmodel"><span class="math display">\[
y_{ij} = \mu + \tau_{k(i)} + a_i + e_{ij}
\tag{10.9}\]</span></span></p>
<p>여기서 <span class="math inline">\(\tau_{k(i)}\)</span>는 <span class="math inline">\(i\)</span>번째 학교의 교수법에 대한 고정효과이다(교수법이 배정된 결과에 의하여 <span class="math inline">\(k(i)=1\)</span> 또는 <span class="math inline">\(k(i)=2\)</span>이 된다). 이 교수법에 대한 고정효과에 대해서는 두 교수법이 차이가 있는 지에 대한 검정이 주요한 관심사일 것이다 (<span class="math inline">\(H_0: \tau_1=\tau_2\)</span>)</p>
<div class="callout callout-style-default callout-caution callout-titled" title="고정효과와 임의효과의 표기">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
고정효과와 임의효과의 표기
</div>
</div>
<div class="callout-body-container callout-body">
<p>고정효과는 보통 모형식에서 그릭 문자(<span class="math inline">\(\alpha\)</span>, <span class="math inline">\(\beta\)</span>)로 표시하고 임의효과는 모형식에서 영어 알파벳 문자(<span class="math inline">\(a\)</span>, <span class="math inline">\(b\)</span>)로 표시한다</p>
</div>
</div>
</section>
</section>
<section id="반복측정자료" class="level2" data-number="10.3">
<h2 data-number="10.3" class="anchored" data-anchor-id="반복측정자료"><span class="header-section-number">10.3</span> 반복측정자료</h2>
<p>반복측정자료(longitudinal data, repeated measurements)는 관측단위안에서 여러 개의 관측값을 측정한 자료의 형식을 말한다. 예를 들어 환자가 병원을 여러 번 방문하고 방문시마다 혈압을 측정하였다면 한 명의 환자에서 반복 측정한 자료는 서로 독립이 아니다. 또한 가구조사(household survey)에서 가구원의 취업 여부, 건겅 상태등을 여러 해동안 매년 측정하는 경우 이러한 자료를 패널자료(panel data) 또는 longitudinal 자료라고 한다. 이렇게 하나의 관측단위 안에서 측정한 자료들은 서로 독립이 아닌 특징이 있고 자료를 분석하는 경우 이러한 자료들의 종속구조를 고려하는 모형을 사용하는 것이 적절하다. 이렇게 반복측정자료에서 반복자료들의 공분산구조를 설정하는 통계적 방법들은 다양하지만 대표적으로 쉽게 사용할 수 있는 방법이 임의효과를 포함한 혼합모형을 사용하는 방법이다.</p>
<div id="exm-sleep" class="theorem example">
<p><span class="theorem-title"><strong>보기 10.1 (트럭운전사의 수면시간)</strong></span> <code>lme4</code> 패키지에 자료인 <code>spleepstudy</code>는 화물트럭 운전사들에 대한 수면부족 현상에 대하여 연구한 자료이다. 18명의 운전자들이 매일 3시간의 수면(부족한 수면)을 하면서 매일 일정한 동작의 반응시간을 10일동안 반복적으로 측정한 자료가 있다. 한명의 운전사에게 10일 동안의 반응에 대한 측정자료 10개가 존재하므로 이는 반복측정 자료이며 이러한 10개의 자료는 독립이 아니다. 일단 자료의 구조를 살펴보자. 반응변수 `<code>Reaction</code>은 반응시간(ms)를 나타내며 설명변수로서 <code>Days</code>는 날짜(<span class="math inline">\(t=0,1,2,\dots,9\)</span>), <code>Subject</code> 는 운전자의 고유번호를 나타낸다.</p>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmerTest)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(sleepstudy)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   180 obs. of  3 variables:
 $ Reaction: num  250 259 251 321 357 ...
 $ Days    : num  0 1 2 3 4 5 6 7 8 9 ...
 $ Subject : Factor w/ 18 levels "308","309","310",..: 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(sleepstudy, <span class="at">n =</span> <span class="dv">20</span>)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Reaction Days Subject
1  249.5600    0     308
2  258.7047    1     308
3  250.8006    2     308
4  321.4398    3     308
5  356.8519    4     308
6  414.6901    5     308
7  382.2038    6     308
8  290.1486    7     308
9  430.5853    8     308
10 466.3535    9     308
11 222.7339    0     309
12 205.2658    1     309
13 202.9778    2     309
14 204.7070    3     309
15 207.7161    4     309
16 215.9618    5     309
17 213.6303    6     309
18 217.7272    7     309
19 224.2957    8     309
20 237.3142    9     309</code></pre>
</div>
</div>
<p>각 운전자에 대한 10일 간의 반응속도가 시간에 따라 어떻게 변하는 가를 알아보자. 전반적으로 시간이 지나면서 운전자들의 반응시간이 증가하고 있음을 알 수 있다. 또한 개인 별로 반응 시간의 변화와 패턴이 다르다는 것을 알 수 있다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sleepstudy, <span class="fu">aes</span>(<span class="at">x =</span> Days, <span class="at">y =</span> Reaction)) <span class="sc">+</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">linewidth =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">facet_wrap</span>(<span class="st">"Subject"</span>, <span class="at">labeller =</span> label_both) <span class="sc">+</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_bw</span>()</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="multivar-anova_files/figure-html/ex15-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<section id="개체들의-선형-회귀모형" class="level3" data-number="10.3.1">
<h3 data-number="10.3.1" class="anchored" data-anchor-id="개체들의-선형-회귀모형"><span class="header-section-number">10.3.1</span> 개체들의 선형 회귀모형</h3>
<p>각 운전자 <span class="math inline">\(i\)</span> 에 대하여 10일간 측정한 반응속도 <span class="math inline">\(y_{ij}\)</span>를 시간에 대하여 선형모형으로 적합하면 개인별 회귀직선을 다음과 같이 표시할 수 있다.</p>
<p><span id="eq-re-lmlist1"><span class="math display">\[
y_{ij} = \beta_{0i} + \beta_{1i} t_j + e_{ij},\quad i=1,2,\dots,18,\quad j=1,2,\dots,10
\tag{10.10}\]</span></span></p>
<p>여기서 오차항 <span class="math inline">\(e_{ij}\)</span>은 서로 독립이며 <span class="math inline">\(N(0, \sigma^2_e)\)</span>를 따른다고 가정한다.</p>
<p>행렬식으로는 다음과 같이 나타낼 수 있다.</p>
<p><span class="math display">\[  
\pmb y_i =\pmb X_i \pmb \beta_{i} +\pmb e_i
\]</span></p>
<p>여기서 <span class="math display">\[
\pmb y_i=\begin{bmatrix}
y_{i1} \\
y_{i2} \\
\vdots \\
y_{i,10}
\end{bmatrix},~ \pmb X_i =
\begin{bmatrix}
1 &amp; 0 \\
1 &amp; 1 \\
\vdots &amp; \vdots  \\
1 &amp; 9
\end{bmatrix}, \pmb \beta_i=
\begin{bmatrix}
\beta_{0i} \\
\beta_{1i} \\
\end{bmatrix}, \pmb e_i=
\begin{bmatrix}
e_{i1} \\
e_{i2} \\
\vdots \\
e_{i,10}
\end{bmatrix}
\]</span></p>
<p>위의 식에서 <span class="math inline">\(\beta_{0i}\)</span>와 <span class="math inline">\(\beta_{1i}\)</span>는 <span class="math inline">\(i\)</span>번째 운전사의 반응속도를 설명내는 회귀직선의 절편과 기울기이다. 절편 <span class="math inline">\(\beta_{0i}\)</span>는 실험 시작때 반응속도를 의미하고 기울기 <span class="math inline">\(\beta_{1i}\)</span>는 실험이 진행되는 동안 반응속도가 어떻게 변하는 지 변화의 방향과 크기를 보여준다. 함수 를 아래와 같이 이용하면 식 <a href="#eq-re-lmlist1" class="quarto-xref">식&nbsp;<span>10.10</span></a> 을 각 운전사마다 적합시켜 각각의 절편과 기울기를 구할 수 있다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>lmf1 <span class="ot">&lt;-</span> <span class="fu">lmList</span>(Reaction <span class="sc">~</span> Days <span class="sc">|</span> Subject, sleepstudy)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>lmf1</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call: lmList(formula = Reaction ~ Days | Subject, data = sleepstudy) 
Coefficients:
    (Intercept)      Days
308    244.1927 21.764702
309    205.0549  2.261785
310    203.4842  6.114899
330    289.6851  3.008073
331    285.7390  5.266019
332    264.2516  9.566768
333    275.0191  9.142045
334    240.1629 12.253141
335    263.0347 -2.881034
337    290.1041 19.025974
349    215.1118 13.493933
350    225.8346 19.504017
351    261.1470  6.433498
352    276.3721 13.566549
369    254.9681 11.348109
370    210.4491 18.056151
371    253.6360  9.188445
372    267.0448 11.298073

Degrees of freedom: 180 total; 144 residual
Residual standard error: 25.59182</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(<span class="fu">coef</span>(lmf1))</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            (Intercept)       Days
(Intercept)   1.0000000 -0.1375534
Days         -0.1375534  1.0000000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">coef</span>(lmf1), <span class="at">main =</span> <span class="st">"intercepts and slopes on drivers: sleep study "</span>)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="multivar-anova_files/figure-html/ex16-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>18개의 절편과 기울기는 큰 상관관계는 없는것으로 보이지만 약한 음의 상관계수가 나타났다.<br>
절편과 기울기에 대한 분포를 보기 위하여 상자그림을 그려보면 평균을 중심으로 대칭인 분포를 보이고 있다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(<span class="fu">coef</span>(lmf1)[<span class="dv">1</span>])</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(<span class="fu">coef</span>(lmf1)[<span class="dv">2</span>])</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="multivar-anova_files/figure-html/box-1.png" style="width:9cm;height:9cm" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="multivar-anova_files/figure-html/box-2.png" style="width:9cm;height:9cm" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>이제 각 운전사에 대하여 회귀식을 따로 적합하지 않고 전체 운전사들의 자료를 모두 합쳐서 하나의 회귀식을 고려할 수 있다. 개체의 특성을 반영하는 모형이 아닌 전체 집단에 대한 평균적인 모형(population model)을 고려하는 것이다.</p>
<p><span id="eq-re-popmodel"><span class="math display">\[
y_{ij} = \beta_0 + \beta_1 t_j + e_{ij} ,\quad i=1,2\dots,18,  j=1,2, \dots, 10
\tag{10.11}\]</span></span></p>
<p>여기서 오차항은 서로 독립이며 <span class="math inline">\(N(0, \sigma^2_e)\)</span>를 따른다고 가정한다.</p>
<p>위와 같은 전체 운전사 집단의 관측값을 운전자의 특성을 고려하지 않고 세운 모형으로서 시간에 따른 반응시간에 대한 모집단의 전체적인 평균적 함수 관계를 파악하는 모형이라고 할 수 있다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>lmpop <span class="ot">&lt;-</span> <span class="fu">lm</span>(Reaction <span class="sc">~</span> Days, sleepstudy)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmpop)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Reaction ~ Days, data = sleepstudy)

Residuals:
     Min       1Q   Median       3Q      Max 
-110.848  -27.483    1.546   26.142  139.953 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  251.405      6.610  38.033  &lt; 2e-16 ***
Days          10.467      1.238   8.454 9.89e-15 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 47.71 on 178 degrees of freedom
Multiple R-squared:  0.2865,    Adjusted R-squared:  0.2825 
F-statistic: 71.46 on 1 and 178 DF,  p-value: 9.894e-15</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(sleepstudy, <span class="fu">plot</span>(Days, Reaction, <span class="at">main =</span> <span class="st">"Population and individual regression lines"</span>))</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">a =</span> <span class="fu">coef</span>(lmpop)[<span class="dv">1</span>], <span class="at">b =</span> <span class="fu">coef</span>(lmpop)[<span class="dv">2</span>], <span class="at">lwd =</span> <span class="dv">3</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">18</span>) {</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    xx <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">coef</span>(lmf1)[i, ])</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">abline</span>(<span class="at">a =</span> xx[<span class="dv">1</span>], <span class="at">b =</span> xx[<span class="dv">2</span>], <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="multivar-anova_files/figure-html/pmodel-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>이제 각 운전사에 대하여 개체별로 적합한 회귀식의 계수들<span class="math inline">\((\hat \beta_{0i}, \hat \beta_{1i})\)</span> 와 전체집단에 적한한 회귀식의 계수 <span class="math inline">\((\hat \beta_{0}, \hat \beta_{1})\)</span>의 관계를 보면 개체별로 회귀 계수들의 평균이 전체에 적용한 모형의 계수와 매우 가까운 사실을 알 수 있다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply</span>(<span class="fu">coef</span>(lmf1), <span class="dv">2</span>, mean)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)        Days 
  251.40510    10.46729 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(lmpop)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)        Days 
  251.40510    10.46729 </code></pre>
</div>
</div>
</section>
<section id="sec-randomcoef" class="level3" data-number="10.3.2">
<h3 data-number="10.3.2" class="anchored" data-anchor-id="sec-randomcoef"><span class="header-section-number">10.3.2</span> 임의계수 모형</h3>
<p>앞 절의 모형과 분석에서 알 수 있듯이 한 개체에 대하여 여러 개의 관측값을 측정한 자료에 회귀방정식을 각각 적합시켜보고 또한 개체의 특성을 고려하지않은 전체 모형을 적합해보면 다음과 같은 두 가지 결과를 볼 수 있다.</p>
<ul>
<li>각 개체별 회귀식은 개인의 특성을 반영한다. 즉, 개체에 따라 시간에 따른 반응시간의 변화가 다르게 나타난다.</li>
<li>하지만 개인별로 볼 때도 전체적으로는 시간에 따라서 반응시간이 증가하는 경향이 있음을 알 수 있다.</li>
<li>전체 자료에 적합한 모형을 보면 개인별로 적합한 모형의 공통적인 성격, 즉 시간에 따른 반응시간의 증가를 알 수 있다.</li>
<li>이러한 결과를 보고 각 개인의 변화는 전체적인 변화를 따르면서 각 개인의 특성이 반영되었다고 가정할 수 있다.</li>
</ul>
<p>위에서 논의하였듯이 전체적인 경향과 개인의 특성을 동시에 고려할 수 있는 모형이 생각할 수 있고 이러한 모형이 다음과 같은 모형이다.</p>
<p><span id="eq-re-repeat"><span class="math display">\[
y_{ij} = (\beta_0 + b_{0i}) + (\beta_1 + b_{1i}) t_j + e_{ij} , \quad i=1,2,\dots,18,\quad j=1,2,\dots,10
\tag{10.12}\]</span></span></p>
<p>모형 <a href="#eq-re-repeat" class="quarto-xref">식&nbsp;<span>10.12</span></a> 는 절편과 기울기가 두 개의 구성 요소로 더해져서 표현된다.기울기는 <span class="math inline">\(\beta_1+b_{1i}\)</span>로서 나타내어지며 <span class="math inline">\(\beta_1\)</span>은 모집단이 가지는 공통적인 경향을 반영하는 모수이고 <span class="math inline">\(b_{1i}\)</span>는 <span class="math inline">\(i\)</span> 번째 개체의 특성을 반영한 확률변수이다. 절편도 유사한 형식으로 구성된다.</p>
<p>각 개인에 대한 특성을 나타내는 변수 <span class="math inline">\((b_{0i}, b_{1i})\)</span> 을 확률변수로 설정하고 이를 모수(<span class="math inline">\(\beta_0, \beta_1)\)</span> (parameter or fixed effect)와 구별하여 임의효과(random effect)라고 한다.</p>
<p>임의효과는 모집단을 구성하는 개인이 표본에 추출되었다고 생각하며 확률분포를 따른다고 가정한다. 반복측정자료에서 인의효과를 공통으로 가지고 있는 관측치는 독립이 아니게 돼며 따라서 같은 개체에서 나온 관측값은 독립이 아니다.</p>
<p>모형 <a href="#eq-re-repeat" class="quarto-xref">식&nbsp;<span>10.12</span></a> 처럼 각 개인의 임의 효과가 포함된 선형모형을 <strong>임의계수모형(random coefficient model)</strong> 이라고 한다. 이러한 모형은 반복측정자료에서 개인의 특성을 고려하여 모형을 설정하는데 유용하다.</p>
<p>18명에 대한 회귀직선의 절편과 기울기를 보면 개인의 차이에 따른 변동을 볼 수 있으며 이러한 각 개인간의 변동을 임의효과 를 이용하여 다음과 같은 모형을 생각해보자.</p>
<p><span class="math display">\[
\pmb \beta_i=
\begin{bmatrix}
\beta_{0} \\
\beta_{1} \\
\end{bmatrix}
+\begin{bmatrix}
b_{0i} \\
b_{1i} \\
\end{bmatrix}
, \quad
\pmb b_i =
\begin{bmatrix}
b_{0i} \\
b_{1i} \\
\end{bmatrix} \sim
N \left (
\begin{bmatrix}
0 \\
0 \\
\end{bmatrix}
,
\begin{bmatrix}
\sigma^2_{b1} &amp; \rho \sigma_{b1} \sigma_{b2}\\
\rho \sigma_{b1} \sigma_{b2} &amp; \sigma^2_{b2} \\
\end{bmatrix}
\right )
\]</span></p>
<p>위의 모형은 각 개인의 회귀직선에서 각 절편과 기울기가 전체평균 <span class="math inline">\(\beta_0\)</span>와 <span class="math inline">\(\beta_1\)</span>를 따르며 각 개인의 차이는 전체평균에 임의효과인 <span class="math inline">\(b_{0i}\)</span>와 <span class="math inline">\(b_{1i}\)</span>가 더해져서 나타난다는 것을 의미한다. 이변량 임의효과 <span class="math inline">\(b_{0i}\)</span>와 <span class="math inline">\(b_{1i}\)</span>는 이변량 정규분포를 따르며 각각의 분산과 상관계수가 <span class="math inline">\(\sigma^2_{b1}\)</span>, <span class="math inline">\(\sigma^2_{b2}\)</span>, <span class="math inline">\(\rho\)</span>이다.</p>
<p>다른 개체에 대한 임의효과는 서로 독립이며 임의 효과와 오차항은 독립이다. 여기서 오차항은 서로 독립이며 <span class="math inline">\(N(0, \sigma^2_e)\)</span>를 따른다고 가정한다.</p>
<p><span class="math display">\[  
Cov(\pmb b_{i}, \pmb b_{j}) =\pmb 0 \text{ when } i \ne j,\quad
Cov(\pmb b_{i}, e_{jk}) =\pmb 0 \text{ for all } i,j,k
\]</span></p>
<p>위 <a href="#eq-re-repeat" class="quarto-xref">식&nbsp;<span>10.12</span></a> 같은 혼합효과모형(mixed effects model)을 각 개인 <span class="math inline">\(i\)</span>에 대하여 행렬식으로 표시하면 다음과 같다. 아래 모형식은 일반적으로 독립군집 모형에서 하나의 군집에 대한 반복된 관측값들에 대한 모형이며 독립군집 모형의 일반적인 이론은 다음 절에서 더 논의할 것이다.</p>
<p><span class="math display">\[  
\pmb y_i = \pmb X_i \pmb \beta + \pmb Z_i \pmb b_i + \pmb e_i , \quad i=1,2,\dots,18
\]</span></p>
<p>여기서</p>
<p><span class="math display">\[  
\pmb y_i=\begin{bmatrix}
y_{i1} \\
y_{i2} \\
\vdots \\
y_{i,10}
\end{bmatrix},~\pmb X_i =
\begin{bmatrix}
1 &amp; 0 \\
1 &amp; 1 \\
\vdots &amp; \vdots  \\
1 &amp; 9
\end{bmatrix}, \pmb  \beta=
\begin{bmatrix}
\beta_{0} \\
\beta_{1} \\
\end{bmatrix}, ~\pmb Z_i =
\begin{bmatrix}
1 &amp; 0 \\
1 &amp; 1 \\
\vdots &amp; \vdots  \\
1 &amp; 9
\end{bmatrix},~ \pmb b_i =
\begin{bmatrix}
b_{0i} \\
b_{1i} \\
\end{bmatrix},~
\pmb  e_i=
\begin{bmatrix}
e_{i1} \\
e_{i2} \\
\vdots \\
e_{i,10}
\end{bmatrix}
\]</span></p>
<p>위의 각 개인에 대한 모형을 모두 합쳐서 하나의 혼합효과모형으로 나타내면 다음과 같이 표현할 수 있다.</p>
<p><span id="eq-re-lme1"><span class="math display">\[
\pmb  y = \pmb  X \pmb \beta + \pmb Z \pmb b + \pmb e
\tag{10.13}\]</span></span></p>
<p>여기서 반응변수벡터 <span class="math inline">\(\pmb y\)</span>와 고정효과 <span class="math inline">\(\pmb \beta\)</span>에 대한 계획행렬 <span class="math inline">\(X\)</span>는 각 개인의 반응변수벡터 <span class="math inline">\(\pmb y_i\)</span>와 <span class="math inline">\(\pmb X_i\)</span>를 행으로 쌓아놓은 것으로 표현된다. 오차항에 대한 벡터 <span class="math inline">\(\pmb e\)</span>도 동일한 형식의 벡터이다.</p>
<p><span class="math display">\[  
\pmb y=\begin{bmatrix}
\pmb y_{1} \\
\pmb y_{2} \\
\vdots \\
\pmb y_{18}
\end{bmatrix},~\pmb X =
\begin{bmatrix}
\pmb X_1 \\
\pmb X_2 \\
\vdots \\
\pmb  X_{18}
\end{bmatrix}
~ \pmb e =
\begin{bmatrix}
\pmb e_1 \\
\pmb e_2 \\
\vdots  \\
\pmb e_{18}
\end{bmatrix}
\]</span></p>
<p>임의효과 벡터 <span class="math inline">\({\pmb  b}\)</span> 는 각 개인에 대한 임의효과벡터 <span class="math inline">\(\pmb b_i\)</span> 를 행으로 쌓아놓은것과 같고 임의효과에 대한 계획행렬 <span class="math inline">\(\pmb Z\)</span> 는 각 개인의 계획행렬 <span class="math inline">\(\pmb Z_i\)</span> 를 대각원소로 구성하는 행렬이다.</p>
<p><span class="math display">\[
\pmb b=\begin{bmatrix}
\pmb b_{1} \\
\pmb b_{2} \\
\vdots \\
\pmb b_{18}
\end{bmatrix},~\pmb Z =
\begin{bmatrix}
\pmb Z_1 &amp; 0 &amp; \dots &amp; 0 \\
0   &amp; \pmb Z_2 &amp; \dots &amp; 0 \\
\vdots &amp; \vdots &amp; \vdots &amp; \vdots  \\
0 &amp; 0 &amp; \dots &amp; \pmb Z_{18}
\end{bmatrix}
\]</span></p>
<p>혼합모형 <a href="#eq-re-lme1" class="quarto-xref">식&nbsp;<span>10.13</span></a> 를 <code>lmer()</code> 함수를 이용하여 적합시켜보자. 모형에서 <code>(1 + Days|Subject)</code> 이 개체에 대하여 절편과 기울기에 대한 임의효과를 지정한다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>fm1 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Reaction <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> Days <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> Days<span class="sc">|</span>Subject), sleepstudy)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fm1)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: Reaction ~ 1 + Days + (1 + Days | Subject)
   Data: sleepstudy

REML criterion at convergence: 1743.6

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-3.9536 -0.4634  0.0231  0.4634  5.1793 

Random effects:
 Groups   Name        Variance Std.Dev. Corr
 Subject  (Intercept) 612.10   24.741       
          Days         35.07    5.922   0.07
 Residual             654.94   25.592       
Number of obs: 180, groups:  Subject, 18

Fixed effects:
            Estimate Std. Error      df t value Pr(&gt;|t|)    
(Intercept)  251.405      6.825  17.000  36.838  &lt; 2e-16 ***
Days          10.467      1.546  17.000   6.771 3.26e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
     (Intr)
Days -0.138</code></pre>
</div>
</div>
<p>위의 혼합모형 적합결과를 살펴보자. 첫째로 고정효과에 대한 추정식은 다음과 같다</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fixef</span>(fm1)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)        Days 
  251.40510    10.46729 </code></pre>
</div>
</div>
<p>또한 오차항에 대한 분산 및 임의효과의 분산성분과 상관계수는 다음과 같이 나타난다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">VarCorr</span>(fm1)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Groups   Name        Std.Dev. Corr 
 Subject  (Intercept) 24.7407       
          Days         5.9221  0.066
 Residual             25.5918       </code></pre>
</div>
</div>
<p>위의 고정효과와 임의효과의 분산성분에 대한 추정치를 이용하여 모형의 적합의 결과를 다음과 같이 나타낼 수 있다.</p>
<p><span class="math display">\[
\text{Reaction Time} = N(251.405 + 10.467 \text{ Days}, 25.6^2)
\]</span></p>
<p><span class="math display">\[
\begin{bmatrix}
b_{0i} \\
b_{1i} \\
\end{bmatrix} \sim
N \left (
\begin{bmatrix}
0 \\
0 \\
\end{bmatrix}
,
\begin{bmatrix}
24.74^2 &amp; (0.07)(24.74)(5.92)\\
(0.07)(24.74)(5.92)&amp; 5.92^2 \\
\end{bmatrix}
\right )
\]</span></p>
<p>이제 임의효과 <span class="math inline">\(\pmb b\)</span>에 대한 예측(prediction)을 생각해보자. 우리는 오직 관측벡터 <span class="math inline">\(\pmb y\)</span>만을 관측하고 임의효과 <span class="math inline">\(\pmb b\)</span>는 관측을 할 수 없는 확률변수이다. 하지만 주어진 관측벡터와 추정된 분산으로 임의효과의 값을 예측할 수있으며 그 결과는 다음과 같다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>re <span class="ot">&lt;-</span> <span class="fu">ranef</span>(fm1)<span class="sc">$</span>Subject</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>re</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    (Intercept)        Days
308   2.2585510   9.1989758
309 -40.3987381  -8.6196806
310 -38.9604090  -5.4488565
330  23.6906196  -4.8143503
331  22.2603126  -3.0699116
332   9.0395679  -0.2721770
333  16.8405086  -0.2236361
334  -7.2326151   1.0745816
335  -0.3336684 -10.7521652
337  34.8904868   8.6282652
349 -25.2102286   1.1734322
350 -13.0700342   6.6142178
351   4.5778642  -3.0152621
352  20.8636782   3.5360011
369   3.2754656   0.8722149
370 -25.6129993   4.8224850
371   0.8070461  -0.9881562
372  12.3145921   1.2840221</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(re, <span class="at">main =</span><span class="st">"prediction of random effects "</span>)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="multivar-anova_files/figure-html/ex21-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>예측된 각 개인의 절편과 기울기에 대한 임의효과 <span class="math inline">\(b_{0i}\)</span>과 <span class="math inline">\(b_{1i}\)</span>에 고정효과의 추정량 <span class="math inline">\(\hat \beta\)</span>를 더해주면 각 개인의 절편과 기울기에 대한 예측값을 구할 수 있다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>beta <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">as.numeric</span>(<span class="fu">fixef</span>(fm1)),<span class="dv">18</span>,<span class="dv">2</span>,<span class="at">byrow=</span>T)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>beta <span class="sc">+</span> re </span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    (Intercept)       Days
308    253.6637 19.6662617
309    211.0064  1.8476053
310    212.4447  5.0184295
330    275.0957  5.6529356
331    273.6654  7.3973743
332    260.4447 10.1951090
333    268.2456 10.2436499
334    244.1725 11.5418676
335    251.0714 -0.2848792
337    286.2956 19.0955511
349    226.1949 11.6407181
350    238.3351 17.0815038
351    255.9830  7.4520239
352    272.2688 14.0032871
369    254.6806 11.3395008
370    225.7921 15.2897709
371    252.2122  9.4791297
372    263.7197 11.7513080</code></pre>
</div>
</div>
<p>위의 결과를 각 개체에 대해 별도의 회귀직선을 적합시켜서 얻은 18개의 절편과 기울기와 비교해보자.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(lmf1)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    (Intercept)      Days
308    244.1927 21.764702
309    205.0549  2.261785
310    203.4842  6.114899
330    289.6851  3.008073
331    285.7390  5.266019
332    264.2516  9.566768
333    275.0191  9.142045
334    240.1629 12.253141
335    263.0347 -2.881034
337    290.1041 19.025974
349    215.1118 13.493933
350    225.8346 19.504017
351    261.1470  6.433498
352    276.3721 13.566549
369    254.9681 11.348109
370    210.4491 18.056151
371    253.6360  9.188445
372    267.0448 11.298073</code></pre>
</div>
</div>
<p>이렇게 혼합모형을 통해서 얻은 각 개인의 절편과 기울기에 대한 예측값과 각각의 개인에 대해서 회귀직선을 따로 적합하여 얻은 절편과 기울기의 관계를 그림으로 그려보면 다음과 같다. 즉 혼합모형을 통해서 얻은 각 개인의 절편과 기울기는 절편과 기울기의 전체평균값 방향으로 축소되는 경향(shrinkage)을 볼수있다.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="multivar-anova_files/figure-html/ex24-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>여기서 혼합모형의 식 <a href="#eq-re-lme1" class="quarto-xref">식&nbsp;<span>10.13</span></a> 의 임의효과에 대한 계획행렬 <span class="math inline">\(Z\)</span>의 구조를 살펴보자. R 의 적합된 결과에서 <code>getME</code> 함수를 이용하여 계획행렬 <span class="math inline">\(\pmb Z\)</span>의 전치행렬(transpose matrix, <span class="math inline">\(\pmb Z^t\)</span>)을 얻을 수 있다. 계획행렬 <span class="math inline">\(\pmb Z\)</span>는 그 값의 많은 부분이 0으로 구성되어 있어서 성김행렬(saprse matrix)라고 부르며 이런 행렬은 특별한 형식으로 저장되어 있다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">image</span>(<span class="fu">getME</span>(fm1,<span class="st">"Zt"</span>))</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="multivar-anova_files/figure-html/ex25-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>또한 혼합모형의 식 <a href="#eq-re-lme1" class="quarto-xref">식&nbsp;<span>10.13</span></a> 에서 임의효과의 상관계수가 <span class="math inline">\(\rho=0\)</span>인 경우의 모형을 고려해 보자</p>
<p><span class="math display">\[
\begin{bmatrix}
b_{0i} \\
b_{1i} \\
\end{bmatrix} \sim
N \left (
\begin{bmatrix}
0 \\
0 \\
\end{bmatrix}
,
\begin{bmatrix}
\sigma^2_{b1} &amp; 0\\
0 &amp; \sigma^2_{b2} \\
\end{bmatrix}
\right )
\]</span></p>
<p>임의효과의 상관계수가 <span class="math inline">\(\rho=0\)</span>인 모형은 아래와 같이 <code>(1+Days | Subject)</code> 를 사용하는 대신 두 개의 바 <code>||</code> 를 사용한 <code>(1+Days || Subject)</code>으로 적합시키면 결과를 다음과 같이 얻을 수 있다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>fm2 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Reaction <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> Days <span class="sc">+</span> (<span class="dv">1</span><span class="sc">+</span>Days<span class="sc">||</span>Subject), sleepstudy)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 다음 명령어는 위의 명령어와 같은 모형을 적합한다.</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="co"># fm2 &lt;- lmer(Reaction ~ 1 + Days + (1|Subject) + (0+Days|Subject), sleepstudy)</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fm2)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: Reaction ~ 1 + Days + (1 + Days || Subject)
   Data: sleepstudy

REML criterion at convergence: 1743.7

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-3.9626 -0.4625  0.0204  0.4653  5.1860 

Random effects:
 Groups    Name        Variance Std.Dev.
 Subject   (Intercept) 627.57   25.051  
 Subject.1 Days         35.86    5.988  
 Residual              653.58   25.565  
Number of obs: 180, groups:  Subject, 18

Fixed effects:
            Estimate Std. Error      df t value Pr(&gt;|t|)    
(Intercept)  251.405      6.885  18.156  36.513  &lt; 2e-16 ***
Days          10.467      1.560  18.156   6.712 2.59e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
     (Intr)
Days -0.184</code></pre>
</div>
</div>
<p>위의 고정효과와 임의효과의 분산성분에 대한 추정치를 이용하여 모형의 적합의 결과를 다음과 같이 나타낼 수 있다.</p>
<p><span class="math display">\[
\text{Reaction Time} = N(251.405 + 10.467 \text{ Days}, 25.6^2)
\]</span></p>
<p><span class="math display">\[
\begin{bmatrix}
b_{0i} \\
b_{1i} \\
\end{bmatrix} \sim
N \left (
\begin{bmatrix}
0 \\
0 \\
\end{bmatrix}
,
\begin{bmatrix}
25.1^2 &amp; 0\\
0&amp; 6.0^2 \\
\end{bmatrix}
\right )
\]</span></p>
<p>두 모형, 즉 절편과 기울기에 대한 두 임의효과가 종속인지 또는 독립인지에 대한 두 모형을 AIC(Akaike Information Criteris)로 비교하해 보자. 두 모형은 AIC의 값은 거의 동일하지만 임의효과의 상관게수가 0인 모형이 AIC 값이 약간 작으며 상관게수의 추정치가 메우 작으므로 임의효과의 상관게수가 0인 모형을 선택하는 것이 합리적이라고 판단된다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(fm1)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1755.628</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(fm2)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1753.669</code></pre>
</div>
</div>
</section>
</section>
<section id="최대가능도-추정" class="level2" data-number="10.4">
<h2 data-number="10.4" class="anchored" data-anchor-id="최대가능도-추정"><span class="header-section-number">10.4</span> 최대가능도 추정</h2>
<section id="선형회귀모형" class="level3" data-number="10.4.1">
<h3 data-number="10.4.1" class="anchored" data-anchor-id="선형회귀모형"><span class="header-section-number">10.4.1</span> 선형회귀모형</h3>
<p>반응변수가 <span class="math inline">\(y\)</span> 이고 <span class="math inline">\(k\)</span>개의 독립변수 <span class="math inline">\((x_1, x_2, \cdots, x_k)\)</span>가 있다고 가정하고 표본의 크기 <span class="math inline">\(n\)</span> 인 자료가 얻어지면 선형회귀식을 행렬로 다음과 같이 표현할 수 있다.</p>
<p><span class="math display">\[
\begin{aligned}
y_i &amp; = \beta_0 + \beta_1x_{i1} + \beta_2x_{i2} + \cdots + \beta_kx_{ik} + e_i \\
     &amp; = \pmb  x^t_i \pmb  \beta + e_i, \quad i=1,2,\cdots,n
\end{aligned}
\]</span></p>
<p>위와 같은 회귀모형을 선형중회귀모형이라 부르며. 위의 모형식을 벡터와 행렬을 이용하여 표시하면 다음과 같다.</p>
<p><span id="eq-re-linreg1"><span class="math display">\[
\pmb  y = \pmb  X \pmb  \beta + \pmb  e
\tag{10.14}\]</span></span></p>
<p>여기서 회귀분석의 오차항의 가정을 살펴보면 오차항이 서로 독립이고 동일한 분산을 갖는다. 즉, 오차항은 다음의 분포를 따른다. 즉, <span class="math inline">\(\pmb  e  \sim (0,\sigma_e^2 \pmb  I_n)\)</span>. 관측값 벡터 <span class="math inline">\(\pmb  y\)</span> 의 평균과 분산을 보면</p>
<p><span class="math display">\[
E(\pmb  y|\pmb  X) =  \pmb  X \pmb  \beta, \quad
Var(\pmb  y|\pmb  X) =  \sigma_e^2 \pmb  I_n
\]</span></p>
<p>여기서 오차항이 정규분포를 따른다면 (<span class="math inline">\(\pmb  e  \sim N(0,\sigma_e^2 \pmb  I_n)\)</span>) 관측값 벡터 <span class="math inline">\(\pmb  y\)</span> 또한 정규분포를 따른다</p>
<p><span class="math display">\[
\pmb  y \sim N(\pmb  X \pmb  \beta, \sigma_e^2 \pmb  I_n)
\]</span></p>
<p>위의 선형 모형 가정 하에서, 최소제곱 추정량 <span class="math inline">\(\hat {\pmb  \beta}\)</span> (least square estimator)는 다음과 같이 오차제곱합(Error Sum of Sqaures) <span class="math inline">\(SSE\)</span> 를 최소로 하는 추정량이다.</p>
<p><span class="math display">\[
\begin{aligned}
SSE(\pmb  \beta) &amp; =  \sum_{i=1}^n (y_i - \pmb  x_i^t \pmb  \beta)^2 \\
  &amp;= (\pmb  y - \pmb  X \pmb  \beta)^t(\pmb  y - \pmb  X \pmb  \beta) \\
  \hat {\pmb  \beta}  = \arg \min_{\pmb  \beta}~~ &amp; SSE(\pmb  \beta)
\end{aligned}
\]</span> 참고로 최소제곱추정법은 오차항이 반드시 정규분포를 따르지 않아도 적용할 수 있는 방법이다.</p>
<p>따라서 <span class="math inline">\(\hat {\pmb  \beta}\)</span>는 오차제곱합을 최소로 하는 계수 벡터이다. 오차제곱합에 최소제곱 추정량을 사용하면 이를 잔차제곱합(Residual Sum of Squares)라고 하며 이를 <span class="math inline">\(SSE(\hat {\pmb  \beta})\)</span>로 표시한다.</p>
<p><span class="math display">\[
SSE(\hat {\pmb  \beta}) =  (\pmb  y - \pmb  X \hat {\pmb  \beta})^t(\pmb  y - \pmb  X \hat {\pmb  \beta})
\]</span></p>
<p>오차항의 분산에 대한 추정은 정규분포 가정을 오차항에 대한 정규분포를 가정하고 다음과 같은 잔차제곱합의 분포에 대한 결과를 이용하면</p>
<p><span class="math display">\[
SSE(\hat {\pmb  \beta}) \sim \sigma^2_e \chi^2 (n-k-1)
\]</span></p>
<p>오차항의 분산 <span class="math inline">\(\sigma^2_e\)</span>의 불편추정량 <span class="math inline">\(S^2\)</span>을 구할 수 있다.</p>
<p><span class="math display">\[
S^2 = \frac{ SSE(\hat {\pmb  \beta}) }{ (n-k-1)}
=\frac{ \sum_{i=1}^n (y_i - \pmb  x_i^t \hat {\pmb  \beta} )^2 }{ (n-k-1)}
\]</span></p>
<p>여기서 자유도 <span class="math inline">\(n-k-1\)</span>은 자료의 개수 <span class="math inline">\(n\)</span>에서 절편을 포함한 회귀계수의 개수 <span class="math inline">\(k+1\)</span>를 뺀 수이다.</p>
</section>
<section id="최대가능도-추정-1" class="level3" data-number="10.4.2">
<h3 data-number="10.4.2" class="anchored" data-anchor-id="최대가능도-추정-1"><span class="header-section-number">10.4.2</span> 최대가능도 추정</h3>
<p>위에서 오차항에 대한 정규분포를 가정하면 반응변수가 정규분포를 따른다. 이러한 분포가정을 이용하여 회귀계수와 오차항의 분산에 대한 최대가능도 추정법(Maximum likelihoodestimation)을 고려할 수 있다. 선형모형과 정규분포 가정 하에서</p>
<p><span class="math display">\[ \pmb  y \sim N(\pmb  X  \pmb  \beta, \sigma^2_e \pmb  I_n) \]</span></p>
<p><span class="math inline">\(i\)</span> 번째 관측치 <span class="math inline">\(y_i\)</span>는 정규분포 <span class="math inline">\(N(\pmb  x^t_i \pmb  \beta, \sigma^2_e)\)</span>를 따르고 서로 독립이므로 관측치의 가능도함수(likelihood function) <span class="math inline">\(L=L(\pmb  \beta,\sigma^2_e| \pmb  y)\)</span>는 다음과 같다.</p>
<p><span class="math display">\[
\begin{aligned}
L &amp; = L(\pmb  \beta,\sigma^2_e| \pmb  y) \\
   &amp; = \prod^n_{i=1} f(y_i)\\
   &amp; = \prod^n_{i=1}(2 \pi \sigma^2_e)^{-\frac{1}{2}} \exp \left [-\frac{1}{2\sigma^2_e} (y_i-\pmb  x_i^t\pmb  \beta)^2 \right ] \\
   &amp; = (2\pi\sigma^2_e)^{-\frac{n}{2}} \exp \left [ -\frac{1}{2\sigma^2_e}(\pmb  y-\pmb  X \pmb  \beta)^t(\pmb  y-\pmb  X \pmb  \beta) \right ]
\end{aligned}
\]</span></p>
<p>모든 관측값은 독립이기 때문에 그들의 결합 확률함수는 그들의 주변 확률함수의 곱이다. 위의 식으로부터 로그가능도함수(Log likelihood function) <span class="math inline">\(l=l(\pmb  \beta,\sigma^2_e| \pmb  y)\)</span>는 다음과 같이 주어진다.</p>
<p><span class="math display">\[
l=\log L = const -\frac{n}{2}\log \sigma^2_e
-\frac{1}{2\sigma^2_e} (\pmb  y-\pmb  X \pmb  \beta)^t(\pmb  y-\pmb  X \pmb  \beta) \]</span></p>
<p>로그가능도함수 <span class="math inline">\(l\)</span> 을 최대화하는 회귀계수 <span class="math inline">\(\pmb  \beta\)</span> 와 분산 <span class="math inline">\(\sigma^2_e\)</span> 을 찾아야한다. 따라서 로그가능도함수 <span class="math inline">\(l\)</span>을 <span class="math inline">\(\pmb  \beta\)</span>와 <span class="math inline">\(\sigma^2_e\)</span>으로 미분하여 0이 되는 값을 찾으면 그 값이 최대가능도 추정량이다.</p>
<p>여기서 주목할 점은 <span class="math inline">\((y-\pmb  X \pmb  \beta)^t(y-\pmb  X \pmb  \beta)\)</span>가 최소제곱법에서 나타나는 목표함수(오차제곱합)와 동일하다. 로그가능도함수 <span class="math inline">\(l\)</span>을 미분하여 얻은 방정식은 다음과 같다.</p>
<p><span class="math display">\[
\frac{\partial l(\pmb  \beta , \sigma^2_e)}{\partial\pmb  \beta}
  = -\frac{1}{2\sigma^2_e}(2\pmb  X^t\pmb  X  \pmb  \beta - 2\pmb  X ^t\pmb  y) =0
\]</span></p>
<p><span class="math display">\[
\frac{\partial l(\pmb  \beta , \sigma^2_e)}{\partial \sigma^2_e}
  = -\frac{n}{2 \sigma^2_e }+\frac{1}{2\sigma^4_e}(\pmb  y-\pmb  X \pmb  \beta)^t(\pmb  y-\pmb  X\pmb  \beta) =0
\]</span></p>
<p>위의 최대가능도 추정량 <span class="math inline">\(\hat\beta\)</span>와 <span class="math inline">\(\hat\sigma^2_e\)</span> 에 대한 방정식을 풀면 다음과 같이 쓸 수 있다.</p>
<p><span class="math display">\[
\hat {\pmb  \beta}           = (\pmb  X^t\pmb  X)^{-1} \pmb  X^t\pmb  y
\]</span></p>
<p><span class="math display">\[
\hat \sigma^2_e      = \frac{1}{n}(\pmb  y-\pmb  X \hat {\pmb  \beta})^t(\pmb  y-\pmb  X \hat {\pmb  \beta}) = \frac{1}{n} SSE(\hat {\pmb  \beta})
\]</span></p>
<p>그러므로 최대가능도 추정량 <span class="math inline">\(\hat {\pmb  \beta}\)</span>는 최소제곱 추정량과 같다. 여기서 오차 분산의 최대가능도추정량 <span class="math inline">\(\hat \sigma^2_e\)</span>는 편향되어진다(biased estimator).</p>
<p><span class="math display">\[
E(\hat \sigma^2_e) = \frac{n-k-1}{n} \sigma^2_e \ne \sigma^2_e
\]</span></p>
<p>결과적으로 불편 추정량 <span class="math inline">\(S^2 =\frac{SSE(\hat {\pmb  \beta})}{(n-k-1)}\)</span>과 유사한 것을 선호한다. 그러나, n이 증가할 때, 그 <span class="math inline">\(\hat\sigma^2_e\)</span> 편향은 <span class="math inline">\(0\)</span>으로 감소하게된다.</p>
<p>하나 주목할 점은 가능도함수에 최대가능도추정량을 대입하면 그 값이 <span class="math inline">\(SSE(\hat {\pmb  \beta})\)</span>의 함수로 나타난다.</p>
<p><span class="math display">\[
\begin{aligned}
L(\hat {\pmb  \beta} ,\hat \sigma^2_e ) &amp; =
(2\pi\hat \sigma^2_e)^{-\frac{n}{2}} \exp \left [-\frac{1}{2 \hat \sigma^2_e}(\pmb  y-\pmb  X \hat {\pmb  \beta})^t(\pmb  y-\pmb  X \hat {\pmb  \beta} ) \right ] \\
&amp; = (2\pi\hat \sigma^2_e)^{-\frac{n}{2}} \exp \left [-\frac{n}{2} \right ] \\
&amp; = \exp \left [-\frac{n}{2} \right ] \left (2\pi \frac{SSE(\hat {\pmb  \beta})}{n} \right )^{-\frac{n}{2}}\\
l(\hat {\pmb  \beta} ,\hat \sigma^2_e ) &amp;=
\text{constant}  - \frac{n}{2} \log SSE(\hat {\pmb  \beta})
\end{aligned}
\]</span></p>
<p>따라서 잔차제곱함 <span class="math inline">\(SSE(\hat {\pmb  \beta})\)</span> 작아지면 가능도함수는 커진다.</p>
</section>
<section id="선형혼합효과모형의-구조" class="level3" data-number="10.4.3">
<h3 data-number="10.4.3" class="anchored" data-anchor-id="선형혼합효과모형의-구조"><span class="header-section-number">10.4.3</span> 선형혼합효과모형의 구조</h3>
<p>이번 절에서는 일반적인 선형모형에 임의효과가 추가되는 선형혼합효과모형의 예제를 통하여 선형혼합모형의 구조를 살펴보고자 한다.</p>
<p>먼저 <a href="#eq-re-onewayrandom" class="quarto-xref">식&nbsp;<span>10.8</span></a> 에 주어진 일원배치 혼합효과 모형(one-way random effect model)은 선형혼합효과모형의 가장 단순한 구조이다.</p>
<p><span id="eq-re-onewayrandom2"><span class="math display">\[
y_{ij} = \mu + a_i + e_{ij}, \quad i=1,2,\dots,I \text{ and } j=1,2,\dots, J
\tag{10.15}\]</span></span></p>
<p>여기서</p>
<ol type="1">
<li><p><span class="math inline">\(a_i,i=1,2,\dots,I\)</span> 는 첫 번째 계층(군집)의 표본 효과(예를 들어 학교 효과)를 나타내는 임의효과이며 서로 독립이고 <span class="math inline">\(N(0,\sigma_a^2)\)</span>를 따른다.</p></li>
<li><p>계층내에서 관측값(예를 들어 학생)에 대한 오차항 <span class="math inline">\(e_{ij}\)</span>는 서로 독립이며 <span class="math inline">\(N(0,\sigma_e^2)\)</span>를 따른다.</p></li>
<li><p>임의효과 <span class="math inline">\(a_i\)</span>와 오차항 <span class="math inline">\(e_{ij}\)</span>는 서로 독립이다.</p></li>
</ol>
<p>위와 같은 일원배치 혼합효과 모형을 각 개체 <span class="math inline">\(i\)</span>에 대하여 행렬식으로 표시하면 다음과 같다.</p>
<p><span class="math display">\[
\pmb  y_i = \pmb  X_i \pmb  \beta + \pmb  Z_i  b_i + \pmb  e_i , \quad i=1,2,\cdots,I
\]</span></p>
<p>여기서 </p>
<p>위의 각 개체에 대한 혼합효과모형을 합쳐서 아래와 같은 행렬식으로 표현할 수 있다.</p>
<p><span class="math display">\[
\pmb y_i =
\begin{bmatrix}
y_{i1} \\
y_{i2} \\
\vdots \\
y_{iJ}
\end{bmatrix},
\quad
\pmb X_i =
\begin{bmatrix}
1 \\
1 \\
\vdots \\
1
\end{bmatrix},
\quad
\pmb \beta =
\begin{bmatrix}
\mu
\end{bmatrix},
\quad
\pmb Z_i =
\begin{bmatrix}
1 \\
1 \\
\vdots \\
1
\end{bmatrix},
\quad
\pmb a_i =
\begin{bmatrix}
a_i
\end{bmatrix},
\quad
\pmb e_i =
\begin{bmatrix}
e_{i1} \\
e_{i2} \\
\vdots \\
e_{iJ}
\end{bmatrix}, i=1,2,\cdots,I
\]</span> 이제 모든 개체에 대한 혼합효과모형을 하나의 행렬식으로 표현하면 다음과 같다.</p>
<p><span id="eq-re-lme2"><span class="math display">\[
\pmb y = \pmb  X \pmb  \beta + \pmb Z \pmb  a + \pmb  e
\tag{10.16}\]</span></span></p>
<p>여기서 <a href="#eq-re-lme2" class="quarto-xref">식&nbsp;<span>10.16</span></a> 의 각 행렬과 벡터는 다음과 같이 표현된다.</p>
<p><span class="math display">\[
\pmb y =
\begin{bmatrix}
\pmb y_1 \\
\pmb y_2 \\
\vdots \\
\pmb y_I
\end{bmatrix},
\quad
\pmb X =
\begin{bmatrix}
\pmb X_1 \\
\pmb X_2 \\
\vdots \\
\pmb X_I
\end{bmatrix}
=
\begin{bmatrix}
1 \\
1 \\
\vdots \\
1 \\
1 \\
1 \\
\vdots \\
1 \\
\vdots \\
1 \\
1 \\
\vdots \\
1
\end{bmatrix}
\]</span></p>
<p><span class="math display">\[
\pmb Z =
\begin{bmatrix}
\pmb Z_1 &amp; 0        &amp; \dots &amp; 0 \\
0        &amp; \pmb Z_2 &amp; \dots &amp; 0 \\
\vdots   &amp; \vdots   &amp; \ddots &amp; \vdots \\
0        &amp; 0        &amp; \dots &amp; \pmb Z_I
\end{bmatrix}
=
\begin{bmatrix}
1      &amp; 0      &amp; \dots &amp; 0      \\
1      &amp; 0      &amp; \dots &amp; 0      \\
\vdots &amp; \vdots &amp; \dots &amp; \vdots \\
1      &amp; 0      &amp; \dots &amp; 0      \\
\hdashline
0      &amp; 1      &amp; \dots &amp; 0      \\
0      &amp; 1      &amp; \dots &amp; 0      \\
\vdots &amp; \vdots &amp; \dots &amp; \vdots \\
0      &amp; 1      &amp; \dots &amp; 0      \\
\hdashline
\vdots &amp; \vdots &amp; \dots &amp; \vdots \\
\hdashline
0      &amp; 0      &amp; \dots &amp; 1      \\
0      &amp; 0      &amp; \dots &amp; 1      \\
\vdots &amp; \vdots &amp; \dots &amp; \vdots \\
0      &amp; 0      &amp; \dots &amp; 1
\end{bmatrix}
,\quad
\pmb a =
\begin{bmatrix}
a_1 \\
a_2 \\
\vdots \\
a_I
\end{bmatrix}
\]</span></p>
<p><span class="math display">\[
\pmb e =
\begin{bmatrix}
\pmb e_1 \\
\pmb e_2 \\
\vdots \\
\pmb e_I
\end{bmatrix}
=
\begin{bmatrix}
e_{11} \\
e_{12} \\
\vdots \\
e_{1J} \\
\hdashline
e_{21} \\
e_{22} \\
\vdots \\
e_{2J} \\
\hdashline
\vdots \\
\hdashline
e_{I1} \\
e_{I2} \\
\vdots \\
e_{IJ}
\end{bmatrix}
\]</span></p>
<p>위의 행렬식에서 <span class="math inline">\(\pmb  y\)</span> 는 <span class="math inline">\(IJ \times 1\)</span> 의 관측값을 가지는 반응변수 벡터이고 <span class="math inline">\(\pmb X\)</span> 는 전체평균 <span class="math inline">\(\mu\)</span>에 대한 설계행렬(design matrix)로 모두 1인 값을 가지는 <span class="math inline">\(IJ \times 1\)</span> 벡터이다. 여기서 반응변수벡터 <span class="math inline">\(\pmb  y\)</span>와 고정효과 <span class="math inline">\(\pmb  \beta\)</span>에 대한 계획행렬 <span class="math inline">\(X\)</span>는 각 개인의 반응변수벡터 <span class="math inline">\(\pmb  y_i\)</span>와 <span class="math inline">\(\pmb  X_i\)</span>를 행으로 쌓아놓은 것으로 표현된다. 오차항에 대한 벡터 <span class="math inline">\(\pmb  e\)</span>도 동일한 형식의 벡터이다.</p>
<p>임의효과 벡터 <span class="math inline">\(\pmb a\)</span>는 각 개인에 대한 임의효과 <span class="math inline">\(a_i\)</span>를 행으로 쌓아놓은것과 같고 임의효과에 대한 계획행렬 <span class="math inline">\(\pmb  Z\)</span>는 각 개인의 계획행렬 <span class="math inline">\(\pmb  Z_i\)</span>를 대각원소로 같은 행렬이다.</p>
<p>임의효과 벡터 <span class="math inline">\(\pmb  a\)</span>는 <span class="math inline">\(I\)</span> 개의 임의효과를 가지는 벡터이고 그 분포는 평균이 0이고 공분산행렬이 <span class="math inline">\(\sigma^2_a I\)</span>를 가지는 다변량 정규분포를 따른다. 오차항의 벡터는 일반적인 선형모형과 같이 평균이 0 이고 분산이 <span class="math inline">\(\sigma_e^2 I\)</span>인 다변량정규분포를 따른다고 가정한다.</p>
<p><span class="math display">\[
\pmb  a \sim N(\pmb  0, \sigma^2_a \pmb  I_{I}), \quad \pmb  e \sim N(\pmb  0, \sigma^2_e \pmb  I_{IJ})
\]</span></p>
<p>여기서 주의할 점은 오차항의 분산과는 달리 임의효과의 분산 <span class="math inline">\(\sigma^2_a\)</span>의 가능한 값의 범위는 0을 포함한 양수이다. 따라서 분산 <span class="math inline">\(\sigma^2_a\)</span>의 추정값은 0의 값을 가질수 있으며 이러한 경우는 첫번 째 계층에서 나오는 변동이 없다는 것을 의미한다.</p>
<p>임의효과에 대한 설계행렬(design matrix) <span class="math inline">\(\pmb  Z\)</span>는 <span class="math inline">\(IJ \times I\)</span>의 행렬로서 원소의 값이 1 또는 0인 행렬이며 이 설계행렬은 각각의 관측치 <span class="math inline">\(y_{ij}\)</span>에 해당하는 임의효과 <span class="math inline">\(a_i\)</span>를 지정해주는 역활을 한다.</p>
</section>
<section id="선형혼합모형의-분포" class="level3" data-number="10.4.4">
<h3 data-number="10.4.4" class="anchored" data-anchor-id="선형혼합모형의-분포"><span class="header-section-number">10.4.4</span> 선형혼합모형의 분포</h3>
<p>일반적인 선형혼합모형은 다음과 같은 행렬식을 통해 표현할 수 있다.</p>
<p><span class="math display">\[
\pmb  y=\pmb  X \pmb  \beta+ \pmb  Z \pmb  b+\pmb  e
\]</span></p>
<p>여기서 <span class="math inline">\(\pmb  y\)</span> 는 <span class="math inline">\(n \times 1\)</span> 벡터로 반응변수이다. <span class="math inline">\(\pmb  X\)</span>는 <span class="math inline">\(n \times p\)</span> 차원으로 설명변수로 이루어진 행렬이며 절편항과 <span class="math inline">\(p-1\)</span>개의 독립변수를 포함한다(따라서 절편을 포함한 설명변수의 수는 <span class="math inline">\(p\)</span>개이다). <span class="math inline">\(\pmb  \beta\)</span>는 <span class="math inline">\(p \times 1\)</span>의 고정 효과 벡터이다.</p>
<p><span class="math inline">\(\pmb  Z\)</span>는 <span class="math inline">\(n \times q\)</span> 행렬이며 임의효과를 고려한 설명변수 벡터로 특수한 형태를 갖는다. <span class="math inline">\(\pmb  b\)</span>는 <span class="math inline">\(q \times 1\)</span>의 임의효과 벡터이고 오차항 <span class="math inline">\(\pmb  e\)</span>은 <span class="math inline">\(n \times 1\)</span> 확률벡터이다.</p>
<p>이 때 임의효과 <span class="math inline">\(\pmb  b\)</span>와 잔차 <span class="math inline">\(\pmb  e\)</span>는 각각 <span class="math inline">\(\pmb  b \sim N(0,\pmb  G), \pmb  e \sim N(0,\sigma_e^2 \pmb  I_n)\)</span>을 따르며 <span class="math inline">\(\pmb  b\)</span>와 <span class="math inline">\(\pmb  e\)</span>는 서로 독립이다. 따라서 <span class="math inline">\(\pmb  y\)</span>의 평균과 분산은 다음과 같이 표현된다.</p>
<p><span class="math display">\[
\begin{aligned}
E( \pmb  y) &amp; = \pmb  X \pmb  \beta \\
Var( \pmb  y) &amp; = Var( \pmb  X \pmb  \beta+ \pmb  Z \pmb  b+\pmb  e ) \\
   &amp; = Var(\pmb  Z \pmb  b) + Var( \pmb  e) \\
   &amp; = \pmb  Z \pmb  G \pmb  Z^{t}+\sigma_e^2 \pmb  I_n \\
   &amp; \equiv \pmb  V
\end{aligned}
\]</span></p>
<p>또한 만약 임의효과 <span class="math inline">\(\pmb  b\)</span>가 주어졌을 경우 <span class="math inline">\(\pmb  y\)</span>의 조건부 분포는 <span class="math inline">\(N(\pmb  X \pmb  \beta+ \pmb  Z \pmb  b,\sigma^2 \pmb  I_n)\)</span> 이므로 조건부 평균과 분산은 다음과 같다.</p>
<p><span class="math display">\[
\begin{aligned}
E(\pmb  y| \pmb  b) &amp; =\pmb  X \pmb  \beta + \pmb  Z \pmb  b \\
Var(\pmb  y| \pmb  b) &amp; = \sigma_e^2 \pmb  I_n
\end{aligned}
\]</span></p>
<p>임의효과 <span class="math inline">\(\pmb  b\)</span>의 공분산 행렬은 <span class="math inline">\(\pmb  G\)</span>는 임의효과의 구조에 따라 그 형태가 정해지는 공분산 행렬이며 임의효과들 사이의 상관성을 나타낼 수 있다.</p>
<p>또한 관측벡터의 공분산행렬은 <span class="math inline">\(\pmb  V =\pmb  Z \pmb  G \pmb  Z^t + \sigma^2_e \pmb  I\)</span>이고 이 행렬은 관측값들의 분산과 공분산을 나타낸다.</p>
<p>따라서 선형혼합모형에서 추정해야 할 모수들은 고정효과인 <span class="math inline">\(\pmb  \beta\)</span>, 임의효과의 분산인 <span class="math inline">\(\pmb  G\)</span>, 오차의 분산인 <span class="math inline">\(\sigma_e^2\)</span>이 된다.</p>
<p>여기서 관측벡터의 공분산 행렬 <span class="math inline">\(\pmb  V\)</span>의 형태를 앞에서 본 두 예제들 경우에 살펴보자.</p>
<div id="exm-re01" class="theorem example">
<p><span class="theorem-title"><strong>보기 10.2 (일원배치모형: <span class="math inline">\(I=3, J=2\)</span>인 경우)</strong></span> 일원배치모형 <a href="#eq-re-onewayrandom2" class="quarto-xref">식&nbsp;<span>10.15</span></a> 에서 층(그룹)의 수가 3개이고(<span class="math inline">\(I=3\)</span>) 각 층에서 관측치가 2개(<span class="math inline">\(J=2\)</span>)인 경우 임의효과 <span class="math inline">\(\pmb  b\)</span>와 공분산 행렬 <span class="math inline">\(\pmb  G\)</span>이 다음과 같다. 여기서 유의할 점은 임의 벡터의 공분산행렬 <span class="math inline">\(\pmb  G\)</span>에서 추정해야할 모수는 <span class="math inline">\(\sigma^2_a\)</span> 하나이다.</p>
<p><span class="math display">\[
\pmb  b=
\begin{bmatrix}
a_{1} \\
a_{2} \\
a_{3}
\end{bmatrix}
, \quad
\pmb  G = Cov(\pmb  b) =  
\begin{bmatrix}
\sigma^2_a &amp; 0 &amp; 0 \\
0 &amp; \sigma^2_a &amp; 0 \\
0 &amp; 0 &amp; \sigma^2_a
\end{bmatrix}
\]</span></p>
<p>또한 각 개체에 대한 임의효과에 대한 계획행렬 <span class="math inline">\(\pmb  Z_i\)</span>와 전체 계획행렬 <span class="math inline">\(\pmb  Z\)</span>는 다음과 같이 나타나고</p>
<p><span class="math display">\[
\pmb  Z_i = \pmb  Z_* =
\begin{bmatrix}
1  \\
1  \\
\end{bmatrix}
, ~i=1,2,3 \quad
\pmb  Z =
\begin{bmatrix}
1 &amp; 0 &amp; 0 \\
1 &amp; 0 &amp; 0 \\
0 &amp; 1 &amp; 0 \\
0 &amp; 1 &amp; 0 \\
0 &amp; 0 &amp; 1 \\
0 &amp; 0 &amp; 1 \\
\end{bmatrix}
=
\begin{bmatrix}
\pmb  Z_1 &amp; \pmb  0 &amp; \pmb  0 \\
\pmb  0 &amp; \pmb  Z_2 &amp; \pmb  0 \\
\pmb  0 &amp; \pmb  0 &amp; \pmb  Z_3 \\
\end{bmatrix}
\]</span></p>
<p>또한 <span class="math inline">\(\pmb  G \pmb  \Sigma \pmb  Z^t\)</span>은 다음과 같이 나타난다.</p>
<p><span class="math display">\[
\begin{aligned}
\pmb  Z \pmb  G \pmb  Z^t
&amp; =
\begin{bmatrix}
\pmb  Z_1 &amp; \pmb  0 &amp; \pmb  0 \\
\pmb  0 &amp; \pmb  Z_2 &amp; \pmb  0 \\
\pmb  0 &amp; \pmb  0 &amp; \pmb  Z_3 \\
\end{bmatrix}
\begin{bmatrix}
\sigma^2_a &amp; 0 &amp; 0 \\
0 &amp; \sigma^2_a &amp; 0 \\
0 &amp; 0 &amp; \sigma^2_a
\end{bmatrix}
\begin{bmatrix}
\pmb  Z_1 &amp; \pmb  0 &amp; \pmb  0 \\
\pmb  0 &amp; \pmb  Z_2 &amp; \pmb  0 \\
\pmb  0 &amp; \pmb  0 &amp; \pmb  Z_3 \\
\end{bmatrix}^t \\
&amp; =
\begin{bmatrix}
\sigma^2_a \pmb  Z_1 \pmb  Z_1^t &amp; \pmb  0 &amp; \pmb  0 \\
\pmb  0 &amp; \sigma^2_a \pmb  Z_2 \pmb  Z_2^t &amp; \pmb  0 \\
\pmb  0 &amp; \pmb  0 &amp; \sigma^2_a \pmb  Z_3 \pmb  Z_3^t\\
\end{bmatrix}
\end{aligned}
\]</span></p>
<p>이때 <span class="math inline">\(\pmb  Z_i\pmb  Z_i^t\)</span>의 형태는 모두 <span class="math inline">\(\pmb  Z_*\pmb  Z_*^t\)</span>로 모두 동일하고 다음과 같으므로</p>
<p><span class="math display">\[
\pmb  Z_i\pmb  Z_i^t = \pmb  Z_* \pmb  Z_*^t  =
\begin{bmatrix}
1  \\
1  \\
\end{bmatrix}
\begin{bmatrix}
1  &amp; 1
\end{bmatrix}
=
\begin{bmatrix}
1  &amp; 1\\
1  &amp; 1\\
\end{bmatrix}
\]</span></p>
<p>위에서 행렬 $Z G Z^t $는 3개의 <span class="math inline">\(2 \times 2\)</span> 행렬이 대각(diagonal)으로 배치된 형태로서 다음과 같이 나타낼 수 있다.</p>
<p><span class="math display">\[
\pmb  Z \pmb  G \pmb  Z^t = diag \{\sigma^2_a \pmb  Z_i \pmb  Z_i^t \}_{i=1}^3
\]</span></p>
<p>여기서 <span class="math inline">\(diag \{ \pmb  A_i \}_{i=1}^q\)</span> 기호는 행렬 <span class="math inline">\(\pmb  A_i\)</span>들을 <span class="math inline">\(i\)</span>번째 대각위치로 구성하는 행렬을 나타낸다. 또한 관측벡터의 공분산 행렬 <span class="math inline">\(\pmb  V=\pmb  Z \pmb  G \pmb  Z^t + \sigma^2_e \pmb  I\)</span>는 다음과 같이 주어진다.</p>
<p><span class="math display">\[
\pmb  V =
\begin{bmatrix}
\sigma^2_b +\sigma^2_e &amp; \sigma^2_b  &amp; 0 &amp; 0 &amp; 0 &amp; 0\\
\sigma^2_b &amp; \sigma^2_b+\sigma^2_e   &amp; 0 &amp; 0 &amp; 0 &amp; 0\\
0 &amp; 0 &amp;\sigma^2_b +\sigma^2_e&amp; \sigma^2_b &amp;  0 &amp; 0\\
0 &amp; 0 &amp;\sigma^2_b &amp; \sigma^2_b +\sigma^2_e&amp;  0 &amp; 0\\
0 &amp; 0 &amp; 0 &amp; 0 &amp; \sigma^2_b +\sigma^2_e&amp; \sigma^2_b  \\
0 &amp; 0 &amp; 0 &amp; 0 &amp; \sigma^2_b &amp; \sigma^2_b+\sigma^2_e  \\
\end{bmatrix}
\]</span></p>
<p>또는</p>
<p><span class="math display">\[
\pmb  V = diag \{\sigma^2_b \pmb  Z_i \pmb  Z_i^t \}_{i=1}^3 + \sigma^2_e \pmb  I_6
\]</span></p>
<p>같은 그룹에 속한 관측값의 공분산은 <span class="math inline">\(\sigma^2_b\)</span>이고 상관계수는 다음과 같다.</p>
<p><span class="math display">\[
cor(y_{ij}, y_{ik}) = \frac{\sigma^2_b }{\sigma^2_b+\sigma^2_e }
\]</span></p>
</div>
<div id="exm-re02" class="theorem example">
<p><span class="theorem-title"><strong>보기 10.3 (반복측정자료: <span class="math inline">\(I=3, J=4\)</span>인 경우)</strong></span> 반복측정자료 예제에서 임의계수 모형 <a href="#eq-re-repeat" class="quarto-xref">식&nbsp;<span>10.12</span></a> 를 고려하자.</p>
<p>개체가 3개이고(<span class="math inline">\(I=3\)</span>) 반복한 시간의 개수가 4번인 경우(<span class="math inline">\(J=4\)</span>) 각 개체에 대한 임의효과에 대한 계획행렬 <span class="math inline">\(\pmb  Z_i\)</span>와 전체 계획행렬 <span class="math inline">\(\pmb  Z\)</span> 은 다음과 같이 나타난다.</p>
<p><span class="math display">\[
\pmb  Z_i = \pmb  Z_* =
\begin{bmatrix}
1 &amp; t_1 \\
1 &amp; t_2 \\
1 &amp; t_3 \\
1 &amp; t_4
\end{bmatrix}
=
\begin{bmatrix}
1 &amp; 0 \\
1 &amp; 1 \\
1 &amp; 2 \\
1 &amp; 3
\end{bmatrix}
, ~i=1,2,3 \quad
\pmb  Z =
\begin{bmatrix}
\pmb  Z_1 &amp; \pmb  0 &amp; \pmb  0 \\
\pmb  0 &amp; \pmb  Z_2 &amp; \pmb  0  \\
\pmb  0 &amp;   \pmb  0 &amp; \pmb  Z_3  \\
\end{bmatrix}
\]</span></p>
<p>각 개체에 대한 임의효과 벡터 <span class="math inline">\(\pmb  b_i\)</span>의 분포를 다음과 같이 나타내면</p>
<p><span class="math display">\[
\pmb  b_i =
\begin{bmatrix}
b_{0i} \\
b_{1i} \\
\end{bmatrix} \sim
N \left (
\begin{bmatrix}
0 \\
0 \\
\end{bmatrix}
,
\begin{bmatrix}
\sigma_{b11} &amp;  \sigma_{b12} \\
\sigma_{b12} &amp; \sigma_{b22}  \\
\end{bmatrix}
\right )
\]</span></p>
<p>위에서 한 개체에 대한 임의효과 벡터 <span class="math inline">\(\pmb  b_i\)</span>의 공분산을 <span class="math inline">\(\pmb  \Psi\)</span>라고 하자.</p>
<p><span class="math display">\[
\pmb  \Psi =
\begin{bmatrix}
\sigma_{b11} &amp;  \sigma_{b12} \\
\sigma_{b12} &amp; \sigma_{b22}  \\
\end{bmatrix}
\]</span></p>
<p>이제 전체 임의효과 <span class="math inline">\(\pmb  b = (\pmb  b_1^t,\pmb  b_2^t,\pmb  b_3^t)^t\)</span>의 공분산 행렬 <span class="math inline">\(\pmb  G\)</span>은 다음과 같다.</p>
<p><span class="math display">\[
\pmb  G = Cov(\pmb  b) =
\begin{bmatrix}
\pmb  \Psi &amp; \pmb  0 &amp; \pmb  0\\
\pmb  0 &amp; \pmb  \Psi &amp;\pmb  0\\
\pmb  0 &amp; \pmb  0 &amp; \pmb  \Psi
\end{bmatrix}
\]</span></p>
<p>따라서 <span class="math inline">\(\pmb  Z \pmb  G \pmb  Z^t\)</span>은 다음과 같이 나타난다.</p>
<p><span class="math display">\[
\begin{aligned}
\pmb  Z \pmb  G \pmb  Z^t
&amp;=
\begin{bmatrix}
\pmb  Z_1 &amp; \pmb  0 &amp; \pmb  0 \\
\pmb  0 &amp; \pmb  Z_2 &amp; \pmb  0 \\
\pmb  0 &amp; \pmb  0 &amp; \pmb  Z_3 \\
\end{bmatrix}
\begin{bmatrix}
\pmb  \Psi &amp; \pmb  0 &amp; \pmb  0\\
\pmb  0 &amp; \pmb  \Psi &amp;\pmb  0\\
\pmb  0 &amp; \pmb  0 &amp; \pmb  \Psi
\end{bmatrix}
\begin{bmatrix}
\pmb  Z_1 &amp; \pmb  0 &amp; \pmb  0 \\
\pmb  0 &amp; \pmb  Z_2 &amp; \pmb  0 \\
\pmb  0 &amp; \pmb  0 &amp; \pmb  Z_3 \\
\end{bmatrix}^t \\
&amp; =
\begin{bmatrix}
\pmb  Z_1 \pmb  \Psi \pmb  Z_1^t &amp; \pmb  0 &amp; \pmb  0 \\
\pmb  0 &amp; \pmb  Z_2 \pmb  \Psi \pmb  Z_2^t &amp; \pmb  0 \\
\pmb  0 &amp; \pmb  0 &amp;  \pmb  Z_3 \pmb  \Psi \pmb  Z_3^t\\
\end{bmatrix}
\end{aligned}
\]</span></p>
<p>이때 <span class="math inline">\(\pmb  Z_i \pmb  \Psi \pmb  Z_i^t= \pmb  Z_*  \pmb  \Psi\pmb  Z_*^t\)</span>의 형태는 다음과 같이 모두 같으므로</p>
<p><span class="math display">\[
\begin{aligned}
\pmb  Z_i \pmb  \Psi \pmb  Z_i^t &amp;&amp; =\pmb  Z_* \pmb  \Psi \pmb  Z_*^t \\
&amp; =
\begin{bmatrix}
1 &amp; 0 \\
1 &amp; 1 \\
1 &amp; 2 \\
1 &amp; 3
\end{bmatrix}
\begin{bmatrix}
\sigma_{b11} &amp;  \sigma_{b12} \\
\sigma_{b12} &amp; \sigma_{b22}  \\
\end{bmatrix}
\begin{bmatrix}
1  &amp; 1 &amp; 1 &amp; 1\\
0 &amp; 1 &amp; 2 &amp; 3
\end{bmatrix} \\
&amp; =
\begin{bmatrix}
\sigma_{b11} &amp;  \sigma_{b12}\\
\sigma_{b11} + \sigma_{b12}  &amp; \sigma_{b12} + \sigma_{b22} \\
\sigma_{b11} + 2 \sigma_{b12}  &amp; \sigma_{b12} +  2 \sigma_{b22} \\
\sigma_{b11} + 3 \sigma_{b12}  &amp; \sigma_{b12} + 3 \sigma_{b22} \\
\end{bmatrix}
\begin{bmatrix}
1  &amp; 1 &amp; 1 &amp; 1\\
0 &amp; 1 &amp; 2 &amp; 3
\end{bmatrix} \\
&amp; =
\begin{bmatrix}
\sigma_{b11} &amp;  \sigma_{b11} + \sigma_{b12}
   &amp; \sigma_{b11} + 2\sigma_{b12} &amp; \sigma_{b11} + 3\sigma_{b12}\\
\sigma_{b11} + \sigma_{b12}  &amp; \sigma_{b22} + 2\sigma_{b12} + \sigma_{b22}
    &amp;  \sigma_{b22} + 3\sigma_{b12} + 2\sigma_{b22} &amp; \sigma_{b22} + 4\sigma_{b12} + 3\sigma_{b22} \\
\sigma_{b11} + 2\sigma_{b12}  &amp; \sigma_{b22} + 3\sigma_{b12} + 2\sigma_{b22}
    &amp;  \sigma_{b22} + 4\sigma_{b12} + 4\sigma_{b22} &amp; \sigma_{b22} + 5\sigma_{b12} + 6\sigma_{b22} \\
\sigma_{b11} + 3\sigma_{b12}  &amp; \sigma_{b22} + 4\sigma_{b12} + 3\sigma_{b22}
    &amp;  \sigma_{b22} + 5\sigma_{b12} + 6\sigma_{b22} &amp; \sigma_{b22} + 6\sigma_{b12} + 9\sigma_{b22}
\end{bmatrix}
\end{aligned}
\]</span></p>
<p>관측벡터의 공분산 행렬 <span class="math inline">\(\pmb  V=\pmb  Z \pmb  G \pmb  Z^t + \sigma^2_e \pmb  I\)</span>는 다음과 같이 주어진다.</p>
<p><span class="math display">\[
\pmb  V = diag \{\pmb  Z_i \Psi \pmb  Z_i^t \}_{i=1}^3 + \sigma^2_e \pmb  I_{12}
\]</span></p>
<p>같은 그룹에 속한 관측값의 분산과 공분산은 다음과 같이 직접 계산할 수도 있다.</p>
<p><span class="math display">\[
var(y_{ij}) = var((\beta_0 + b_{0i}) + (\beta_1 + b_{1i})t_j + e_{ij})
= \sigma_{b11} + 2 t_j \sigma_{b12} +  t_j^2 \sigma_{b11} +  \sigma_{e}^2
\]</span></p>
<p><span class="math display">\[
\begin{aligned}
cov(y_{ij}, y_{ik}) &amp; = cov[(\beta_0 + b_{0i}) + (\beta_1 + b_{1i})t_j + e_{ij}, ~
(\beta_0 + b_{0i}) + (\beta_1 + b_{1i})t_k + e_{ik} ] \\
&amp;= cov(b_{0i},b_{0i})) + (t_j +t_k) cov(b_{0i},b_{1i})  + t_j t_k cov(b_{1i},b_{1i})  +
cov(e_{ij} ,e_{ik} ) \\
&amp;= \sigma_{b11} +   (t_j +t_k) \sigma_{b12} +  t_j t_k \sigma_{b11} + 0
\end{aligned}
\]</span></p>
<p>따라서 같은 그룹에 속한 두 관측값의 상관계수는 다음과 같다.</p>
<p><span class="math display">\[
cor(y_{ij}, y_{ik}) =
\frac{\sigma_{b11} +   (t_j +t_k) \sigma_{b12} +  t_j t_k \sigma_{b11} }
{\sqrt{ (\sigma_{b11} + 2 t_j \sigma_{b12} +  t_j^2 \sigma_{b11} +  \sigma_{e}^2)
(\sigma_{b11} + 2 t_k \sigma_{b12} +  t_k^2 \sigma_{b11} +  \sigma_{e}^2)} }
\]</span></p>
</div>
</section>
<section id="최대가능도-추정법" class="level3" data-number="10.4.5">
<h3 data-number="10.4.5" class="anchored" data-anchor-id="최대가능도-추정법"><span class="header-section-number">10.4.5</span> 최대가능도 추정법</h3>
<section id="분포의-가정" class="level4" data-number="10.4.5.1">
<h4 data-number="10.4.5.1" class="anchored" data-anchor-id="분포의-가정"><span class="header-section-number">10.4.5.1</span> 분포의 가정</h4>
<p>선형혼합모형에서 모수를 추정하는 방법은 모형이 단순한 경우, 적률법(method of moments)를 이용하여 평균과 분산성분을 추정할 수 있다. 하지만 일반적인 모형에 대하여 각각 적률법을 적용할 제곱합을 설정하고 그 기대값을 구하는것은 어려운 일이다. 따라서 선형혼합모형에서는 정규분포를 가정하고 모수의 추정을 최대가능도 추정법을 사용한다.</p>
<p>잎에서 본 예제들과 같이 선형혼합모형은 각 개체 또는 그룹안에서 관측된 확률변수들은 독립이 아니지만 다른 그룹에서 나온 관측 변수들은 독립을 가정한다. 위와 같은 혼합효과모형(mixed effects model)을 각 개체 <span class="math inline">\(i\)</span>에 대하여 행렬식으로 표시하면 다음과 같다.</p>
<p><span class="math display">\[
\pmb  y_i = \pmb  X_i \pmb  \beta + \pmb  Z_i \pmb  b_i + \pmb  e_i , i=1.2\cdots,I
\]</span></p>
<p>일반적으로 그룹간에서 반복된 관측치를 가지는 모형은 다음과 같은 분포를 고려할 수 있다.</p>
<p><span class="math display">\[
\pmb  b_i \sim_{iid} N( \pmb  0, \sigma^2_e \pmb  \Psi), \quad \pmb  e_i \sim N(\pmb  0, \sigma^2_e \pmb  I)
\]</span></p>
<p>여기서 <span class="math inline">\(\pmb  b_i\)</span>와 <span class="math inline">\(\pmb  e_{i}\)</span>는 독립이다. 위의 가정에서 주의할 점은 임의효과의 공분산행렬을 오차항의 분산 <span class="math inline">\(\sigma^2_e\)</span>과 행렬 <span class="math inline">\(\pmb  \Psi\)</span>의 곱으로 표현한 것이며 그 이유는 최대가능도 추정함수를 좀 더 간결하게 표시하기 위해서이다.</p>
</section>
<section id="가능도함수" class="level4" data-number="10.4.5.2">
<h4 data-number="10.4.5.2" class="anchored" data-anchor-id="가능도함수"><span class="header-section-number">10.4.5.2</span> 가능도함수</h4>
<p>가능도 함수는 반응 벡터 <span class="math inline">\(\pmb  y_i\)</span>의 분포를 이용하여 표현할 수 있다. <span class="math inline">\(\pmb  y_i\)</span>의 분포는 다변량 정규분포를 따르고</p>
<p><span class="math display">\[
E(\pmb  y_i) = \pmb  X_i \pmb  \beta, \quad V(\pmb  y_i) = V_i= \sigma^2_e (\pmb  Z_i \pmb  \Psi \pmb  Z_i^t +\pmb  I )
\]</span></p>
<p>이므로 관측벡터 <span class="math inline">\(\pmb  y_i\)</span>의 차원이 <span class="math inline">\(J\)</span>라면</p>
<p><span class="math display">\[
\begin{aligned}
L(\pmb  \theta | \pmb  y_i) &amp; = f(\pmb  y_i|\pmb  \theta)  \nonumber \\
&amp; =   (2\pi )^{-J/2} |V_i |^{-1/2}
\exp \left [ - \frac{(\pmb  y_i - \pmb  X_i \pmb  \beta )^t V_i^{-1} (\pmb  y_i - \pmb  X_i \pmb  \beta )}{2} \right ] \nonumber \\
&amp; =   (2\pi \sigma^2_e)^{-J/2} |\pmb  Z_i \pmb  \Psi \pmb  Z_i^t +\pmb  I |^{-1/2}
\exp \left [ - \frac{(\pmb  y_i - \pmb  X_i \pmb  \beta )^t [\pmb  Z_i \pmb  \Psi \pmb  Z_i^t +\pmb  I ]^{-1} (\pmb  y_i - \pmb  X_i \pmb  \beta )}{2 \sigma^2_e} \right ]
\end{aligned}
\]</span></p>
<p>여기서 모수벡터 <span class="math inline">\(\pmb  \theta\)</span>는 회귀계수 <span class="math inline">\(\pmb  \beta\)</span>, 임의효과의 공분산 <span class="math inline">\(\Psi\)</span>을 결정하는 분산성분에 대한 모수들 <span class="math inline">\(\pmb  \psi\)</span>, 오차항의 분산 <span class="math inline">\(\sigma^2_e\)</span>를 모아 놓은 벡터이다.</p>
<p>이제 반응값들의 벡터들 <span class="math inline">\(\pmb  y_1, \pmb  y_2, \dots, \pmb  y_I\)</span>들이 모두 독립이므로 모든 관측값을 모아 놓은 관측벡터 <span class="math inline">\(\pmb  y = (\pmb  y_1^t, \pmb  y_2^t, \dots, \pmb  y_I^t)^t\)</span>에 의한 최대가능도 함수는 각각의 최대가능도 함수들을 곱한것과 같다.</p>
<p><span class="math display">\[
L(\pmb  \theta|\pmb  y ) = \prod_{i=1}^I L(\pmb  \theta|\pmb  y_i)
\]</span></p>
<p>위에서 구한 가능도함수는 일반적으로 계산하기가 쉽지 않다. 왜냐하면 관측벡터 <span class="math inline">\(\pmb  y_i\)</span>의 공분산 행렬 <span class="math inline">\(\pmb  V_i\)</span>에 대한 역행렬을 구하는 것이 단순한 모형을 제외하면 일반적으로 쉽지 않다.</p>
</section>
<section id="일원배치모형" class="level4" data-number="10.4.5.3">
<h4 data-number="10.4.5.3" class="anchored" data-anchor-id="일원배치모형"><span class="header-section-number">10.4.5.3</span> 일원배치모형</h4>
<p>선형혼합모형의 가장 기본적인 형태는 앞에서 공부한 <a href="#eq-re-onewayrandom" class="quarto-xref">식&nbsp;<span>10.8</span></a> 의 일원배치모형이다. 하나의 요인이 반응변수에 미치는 영향을 알 수 있는 모형으로 다음과 같이 정의할 수 있다.</p>
<p>일원배치모형의 가능도 함수를 얻기 위해서 <span class="math inline">\(i\)</span>번쨰 관측벡터 <span class="math inline">\(\pmb  y_i\)</span>의 분포를 알아야 한다. <span class="math inline">\(\pmb  y_i\)</span>의 분포는 다음과 같다.</p>
<p><span class="math display">\[
\begin{aligned}
\pmb  y_{i} \sim_{ind} \ N(\mu \pmb  1, \pmb  V_{i}), \ \pmb  V_{i}=\sigma^{2}_{e} \pmb  I+\sigma_{b}^{2} \pmb  1 \pmb  1^t, \quad i=1,2,\dots,I
\end{aligned}
\]</span></p>
<p>여기서 <span class="math inline">\(\pmb  1\)</span>은 모든 원소가 1이고 차원이 <span class="math inline">\(J\)</span> 인 벡터, <span class="math inline">\(\pmb  I\)</span>은 차원이 <span class="math inline">\(J \times J\)</span> 인 항등행렬이다. 또한 모수들은 <span class="math inline">\(\pmb  \theta = (\mu,\sigma_a^2,\sigma_e^2)^t\)</span>으로 구성된다.</p>
<p>따라서 정규분포의 가능도함수를 이용하여 식을 표현하면 다음과 같다.</p>
<p><span class="math display">\[
L(\pmb  \theta | \pmb  y)  = \prod_{i=1}^{I}
(2\pi)^{-J/2} | {\pmb  V}_i|^{-1/2}
\exp \left [  -\frac{1}{2}(\pmb  y_i- \mu {\pmb  1})^{t}{\pmb  V}_{i}^{-1}(\pmb  y_i-\mu {\pmb  1}) \right ]
\]</span></p>
<p>여기서 <span class="math inline">\(V_{i}\)</span>의 행렬식와 역행렬은 각각 <span class="math inline">\(|\pmb  V_{i}| =   (\sigma_e^2 + J \sigma_{b}^{2})(\sigma_e^2)^{J-1}\)</span></p>
<p><span class="math display">\[
{\pmb  V}_{i}^{-1} = \frac{1}{\sigma_e^2} \left [ \pmb  I -\frac{\sigma_{b}^{2}}{\sigma_e^2+J\sigma_{b}^{2}} \pmb  J \right ]
\]</span></p>
<p>위의 결과는 부록의 <a href="math_mat_basic.html#eq-app-det-uvt" class="quarto-xref">식&nbsp;<span>A.3</span></a> 와 <a href="math_mat_basic.html#eq-woodbury" class="quarto-xref">식&nbsp;<span>A.10</span></a> 이용한 것이다. 위 결과를 가능도함수에 대입하여 로그 가능도함수를 구해보면 다음과 같다.</p>
<p><span class="math display">\[
\begin{aligned}
\log L = &amp; -\frac{1}{2}(IJ) \log 2\pi -\frac{1}{2}\sum_{i} \log(\sigma_e^2+J\sigma_{b}^2) - \frac{1}{2}I(J-1)\log\sigma_e ^2 \\
&amp; - \frac{1}{2\sigma_e^2}\sum_{i}\sum_{j} (y_{ij}-\mu)^2 + \frac{J^2\sigma_{b}^2}{2\sigma_e^2}\sum_{i}\frac{(\bar y_{i\cdot}-\mu)^2}{\sigma_e^2 + J \sigma_{b}^{2}}
\end{aligned}
\]</span></p>
<p>여기서 <span class="math inline">\(\bar y_{i.} = \sum_{j=1}^J y_{ij} /J\)</span>이다. 또한 여기서 <span class="math inline">\(\lambda = \sigma_e^{2} + J\sigma_{b}^2\)</span>로 놓으면</p>
<p><span class="math display">\[
\begin{aligned}
\log L = &amp; -\frac{1}{2} (IJ) \log2\pi - \frac{1}{2} I(J-1)\log \sigma_e^2 - \frac{1}{2}I \log \lambda \nonumber \\
&amp; - \frac{SSE}{2\sigma_e^2}-\frac{SSA}{2\lambda}
- \frac{IJ(\bar y_{\cdot\cdot} - \mu)^2 }{2\lambda}
\end{aligned}
\]</span></p>
<p>위 식에서 <span class="math inline">\(SSA = \sum_{i} n (\bar y_{i\cdot} - \bar y_{\cdot\cdot} )^2\)</span>, <span class="math inline">\(SSE = \sum_{i}\sum_{j} (y_{ij}- \bar y_{i\cdot}) ^2\)</span> 이다.</p>
<p>로그가능도함수를 각 모수 <span class="math inline">\((\mu, \sigma^2_e, \lambda)\)</span>에 대해 미분하면 다음과 같은 식이 주어진다.</p>
<p><span class="math display">\[
\begin{aligned}
\frac{\partial \log L}{\partial \mu } &amp; = \frac{IJ(\bar y_{\cdot\cdot} - \mu) }{\lambda} \\
\frac{\partial \log L}{\partial \sigma^2_e } &amp; = -\frac{J(I-1)}{2\sigma^2_e} + \frac{SSE}{\sigma^4_e} \\
\frac{\partial \log L}{\partial \sigma^2_a} &amp; = \frac{-I}{2\lambda} + \frac{SSA}{2\lambda^2}
+\frac{IJ(\bar y_{..}-\mu)^2}{2\lambda^2}
\end{aligned}
\]</span></p>
<p>위의 방정식들을 0으로 놓고 풀면 다음과 같은 추정량의 근을 구할 수 있다.</p>
<p><span class="math display">\[
\tilde \mu = \bar y_{\cdot\cdot},\quad \tilde \sigma_e^2 = MSE = \frac{SSE}{I(J-1)},\quad \tilde \lambda = \frac{SSA}{I}
\]</span></p>
<p>모수 <span class="math inline">\(\lambda = \sigma_e^{2} + J\sigma_{b}^2\)</span>임을 이용하면</p>
<p><span class="math display">\[
\tilde \sigma_{b}^2 = \frac{\hat \lambda - \hat \sigma^2_e}{J} = \frac{SSA/I-MSE}{J}
\]</span> 이다.</p>
<p>위에서 구한 가능도함수의 미분 방정식의 근 <span class="math inline">\((\tilde \mu,\tilde \sigma_e^2,\tilde \sigma_{b}^2 )\)</span> 중에서 평균과 오차항의 추정량은 최대가은도 추정량으로 설정할 수 있지만 임의효과의 분산의 근은 0보다 작은 값이 나올 수 있으므로 다음과 같은 추정량이 최대가능도 추정량이다.</p>
<p><span class="math display">\[
\begin{aligned}
\hat \mu &amp; = \bar y_{\cdot\cdot} \nonumber \\
\hat \sigma_e^2 &amp; = \frac{SSE}{I(J-1)} = MSE  \nonumber \\
\hat \sigma_{b}^2 &amp; =
\begin{cases}
\frac{SSA/I-MSE}{J} &amp; \text{ if } \frac{SSA/I-MSE}{J} \ge 0 \\
0 &amp; \text{ otherwise }
\end{cases}
\end{aligned}
\]</span></p>
<p>위의 최대가능도 추정량을 적률법으로 구한 추정량과 비교하면 평균과 오차항의 추정량은 동일하고 임의효과의 분산 추정량이 다른 점을 알 수 있다.</p>
</section>
<section id="임의효과의-예측" class="level4" data-number="10.4.5.4">
<h4 data-number="10.4.5.4" class="anchored" data-anchor-id="임의효과의-예측"><span class="header-section-number">10.4.5.4</span> 임의효과의 예측</h4>
<p>임의효과는 관측할 수 없는 확률변수이지만 관측값이 주어진 경우 임의효과에 대한 기대값으로 그 값을 예측할 수 있다. 임의효과는 모수가 아니라 확률변수이므로 이에 대한 추론을 추정(estimation)이라고 하지 않고 예측(prediction)이라고 한다.</p>
<p>앞에서 공부한 일원배치모형에서 임의효과 <span class="math inline">\(b_i\)</span>와 그룹의 평균 <span class="math inline">\(\bar y_{i.}\)</span>의 공분산 구해보자.</p>
<p><span class="math display">\[
\begin{aligned}
cov(b_i, \bar y_{i.}) &amp; = cov( b_i, \mu + bi + \bar e_{i.}) \\
  &amp; = cov(b_i, b_i ) \\
  &amp; =var(b_i) \\
  &amp; = \sigma^2_a
\end{aligned}
\]</span></p>
<p>임의효과 <span class="math inline">\(b_i\)</span>와 그룹의 평균 <span class="math inline">\(\bar y_{i.}\)</span>는 각각 다음과 같은 정규분포를 따르므로</p>
<p><span class="math display">\[
b_i \sim N(0, \sigma^2_a), \quad \bar y_{i.} \sim N(\mu, \sigma^2_a + \sigma^2_e/J) \]</span></p>
<p>임의효과 <span class="math inline">\(b_i\)</span>와 그룹의 평균 <span class="math inline">\(\bar y_{i.}\)</span>는 다음과 같은 이변량 정규분포를 따른다.</p>
<p><span class="math display">\[
\begin{bmatrix}
b_i \\
\bar y_{i.}
\end{bmatrix}
\sim
N \left (
\begin{bmatrix}
0 \\
\mu
\end{bmatrix}
, ~
\begin{bmatrix}
\sigma^2_a &amp; \sigma^2_a \\
\sigma^2_a &amp; \sigma^2_a + \sigma^2_e/J
\end{bmatrix}
\right )
\]</span></p>
<p>따라서 그룹의 평균 <span class="math inline">\(\bar y_{i.}\)</span> 이 주어진 경우 임의효과 <span class="math inline">\(b_i\)</span>의 조건부 분포는 정규분포이며 조건부 기대값은 다음과 같이 주어진다 (강의노트 이변량 정규분포 참조). 는 다음과 같다.</p>
<p><span class="math display">\[
E(b_i | \bar y_{i.}) = E(b_i) + \frac{cov(b_i, \bar y_{i.})}{var(\bar y_{i.})} (\bar y_{i.}-E[\bar y_{i.}])
\]</span></p>
<p>따라서</p>
<p><span class="math display">\[
E(b_i | \bar y_{i.}) = \frac{\sigma^2_a}{\sigma^2_a + \sigma^2_e/J } (\bar y_{i.}-\mu)
\]</span></p>
<p>로 주어진다. 위의 식에서 모르는 모수를 최대가능도 추정량으로 대체해주면 임의료과에 대한 예측값을 구할 수 있다.</p>
<p><span id="eq-re-pred1"><span class="math display">\[
\hat b_i = \hat E(b_i | \bar y_{i.}) = \frac{\hat \sigma^2_a}{\hat \sigma^2_a + \hat \sigma^2_e/J } (\bar y_{i.}- \bar y_{..})
\tag{10.17}\]</span></span></p>
<p>위의 <a href="#eq-re-pred1" class="quarto-xref">식&nbsp;<span>10.17</span></a> 을 보면 고정효과를 고려한 일원배치모형 <a href="#eq-re-anova" class="quarto-xref">식&nbsp;<span>10.7</span></a> 에서 각 그룹의 효과 <span class="math inline">\(\alpha_i\)</span>의 추정식 <span class="math inline">\(\hat \alpha_i\)</span>인 다음의 식과 차이가 나는 것을 볼 수 있다.</p>
<p><span class="math display">\[
\hat \alpha_i = y_{i.}- \bar y_{..}
\]</span></p>
<p>임의효과를 이용하면 그룹의 효과가 고정효과를 이용한 모형보다 그 절대값이 작게 나오는 것을 알 수 있다.</p>
<p><span class="math display">\[
\left | \frac{\hat \sigma^2_a}{\hat \sigma^2_a + \hat \sigma^2_e/J } (\bar y_{i.}- \bar y_{..}) \right |
\le  \left  | y_{i.}- \bar y_{..} \right |
\]</span></p>
<p>이러한 현상을 전체 평균으로의 축소현상(shrinkage to grand mean)이라고 부른다.</p>
<p>앞에서 공부한 반복측정자료 에서 혼합모형을 통해서 얻은 각 개인의 절편과 기울기에 대한 예측값과 각각의 개인에 대해서 회귀직선을 따로 적합하여 얻은 절편과 기울기의 관계를 그림으로 그려보면 다음과 같다. 즉 혼합모형을 통해서 얻은 각 개인의 절편과 기울기는 절편과 기울기의 전체평균값 방향으로 축소되는 경향(shrinkage)을 볼수있다.</p>
<!---

### 예제: 고혈압 강하제 살험 


고혈압 환자 66명을 대상으로 32명에게는 기존의 혈압 강하제(C)를 투여하고, 나머지 34명에게는 새로운 혈압 강하제(E)를 투여하였다. 환자가 치료를 시작하기 전에 혈압을 측정하고(0주) 치료를 받은 후  4주, 8주 후에 2번 반복 측정하였다. 이 실험의 목표는 다음과 같다.

1. 기존의 약과 새로운 혈압 강하제 간의 유의한 차이가 있는가?
2. 방문 시간(`time`)에 따라서 혈압(`bp`)의 차이가 있는가?
3. 약(`trt`)과 방문 시간(`time`) 간에 상호작용(interaction)이 있는가?

이제 자료를 읽어서 `blood_data`에 저장하자.


::: {.cell}

```{.r .cell-code}
blood_data <- read.csv(here("data", "ex0601.txt"), header=T, sep="")
head(blood_data,10)
```

::: {.cell-output .cell-output-stdout}

```
   id trt time  bp
1   1   C    0  95
2   2   C    0 100
3   3   C    0  98
4   4   C    0 114
5   5   C    0 110
6   6   C    0 100
7   7   C    0 100
8   8   C    0 100
9   9   C    0 107
10 10   C    0 101
```


:::
:::


모형식을 고려하기 전에 각 처리 그룹에서 시간에 따른 혈압의 변화를 살펴보자. 패키지 `stats` 의 함수 `interaction.plot` 은 반복측정자료의 관측 시점에 따라서 반응 변수의 평균 변화를 처리 그룹에 대해서 그래프를 그려준다.

강하제를 복용한 후에 평균 혈압은 크게 내려갔지만 8주 후에는 다소 올라가는 경향을 보인다. 


::: {.cell}

```{.r .cell-code}
with(blood_data, interaction.plot(x.factor = time, trace.factor = trt, response = bp))
```

::: {.cell-output-display}
![](multivar-anova_files/figure-html/unnamed-chunk-4-1.png){width=90%}
:::
:::


#### 혼합효과 모형 

반응값 $y_{ijk}$를 $i$ 번째 강하제($i=1,2$)를 복용한 $j$ 번째 환자의 $k$ 시간에 측정한 혈압이라고 하자($j=1,2,..,n_i$, $k=0,1,2$). 

먼저 약을 복용하기 전의 혈압 $y_{ij0}$ 은 처리 전의 기준이 되는 값이다. 따라서 우리는 4주와 8주에 측정한 혈압, $y_{ij1}$와 $y_{ij2}$ 에서 0주에 측정한 혈압 $y_{ij0}$을 뺀 두 개의 차이, $d_{ij1}$ 과 $d_{ij2}$를 반응 변수로 사용할 것이다. 각 환자는 2개의 관측값을 가지며 이는 반복측정 자료이다.

$$ d_{ij1} = y_{ij1} -y_{ij0}, \quad d_{ij2} = y_{ij2} -y_{ij0} $$
새로운 반응변수 $d_{ijk}$는 치료 전의 혈압을 기준으로 하여 치료 후에 혈압이 얼마나 변하였는가를 나타낸다. 따라서 $d_{ijk}$ 값이 작을 수록 약의 효과는 더 좋다고 할 수 있다. 


혈압의 차이를 계산하여 다음과 같이 새로운 데이터프레임을 만들자.


::: {.cell}

```{.r .cell-code}
df0 <- blood_data %>% 
  filter(time == 0) %>% 
  select(id, bp) %>% 
  rename( bp0 = bp)

df1 <- blood_data %>% 
  filter(time != 0)

blood_data1 <- left_join(df1, df0, by='id') %>% 
  mutate(d = bp - bp0)

head(blood_data1 ,10)
```

::: {.cell-output .cell-output-stdout}

```
   id trt time bp bp0   d
1   1   C    4 88  95  -7
2   2   C    4 95 100  -5
3   3   C    4 90  98  -8
4   4   C    4 98 114 -16
5   5   C    4 81 110 -29
6   6   C    4 98 100  -2
7   7   C    4 92 100  -8
8   8   C    4 79 100 -21
9   9   C    4 81 107 -26
10 10   C    4 85 101 -16
```


:::
:::


다시 새로운 자료를 이용하여 처리에 따라서 혈압의 변화를 그림으로 살펴보자.


::: {.cell}

```{.r .cell-code}
with(blood_data1, interaction.plot(x.factor = time, trace.factor = trt, response = d))
```

::: {.cell-output-display}
![](multivar-anova_files/figure-html/unnamed-chunk-6-1.png){width=90%}
:::
:::


이제 다음과 같은 모형을 고려하자.

$$
d_{ijk} = \mu + \alpha_i + \beta_k +  (\alpha\beta)_{ik} + b_{ij} + e_{ijk}, \quad i=1,2 ~~ j=1,...,n_i~~ k=1,2
$$ {#eq-re-bloodtrial} 

일단 반복 측정한 횟수가 2 번이므로 측정 시간은 연속형 변수가 아닌 범주형 변수로 지정한다.

위의 모형식 @eq-re-bloodtrial  에서 각 항의 의미는 다음과 같다.

- $\mu$ : 전체 평균 혈압
- $\alpha_i$ : 혈압 강하제의 효과 ($i=1,2$)
- $\beta_k$ : 시간 효과($k=1,2$)
- $(\alpha\beta)_{ik}$ : 강하제와 시간의 상호작용
- $b_{ij} \sim_{iid} N(0,\sigma_b^2)$ :  환자의 효과를 나타내는 임의효과 ($i=1,2$, $j=1,2,\dots,n_i$)
- $e_{ijk} \sim_{iid} N(0, \sigma_e^2)$:  오차항 

위에서 환자의 효과를 나타내는 임의효과와 오차항은 독립이라고 가정한다.

이제 자료에서 치료약(`trt`), 시간(`time`), 환자의 ID(`id`)를 범주형 변수로 변환하자.


::: {.cell}

```{.r .cell-code}
blood_data1$id <- factor(blood_data1$id)
blood_data1$trt <- factor(blood_data1$trt)
blood_data1$time <- factor(blood_data1$time)
```
:::


이제 다음과 같은 R 명령문을 이용하여 모형 @eq-re-bloodtrial  을 적합하고 추정 결과를 살펴 보자. 


::: {.cell}

```{.r .cell-code}
blood_fit <- lmer(d ~ trt + time + trt*time +(1|id), data=blood_data1)
summary(blood_fit)
```

::: {.cell-output .cell-output-stdout}

```
Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: d ~ trt + time + trt * time + (1 | id)
   Data: blood_data1

REML criterion at convergence: 862

Scaled residuals: 
     Min       1Q   Median       3Q      Max 
-1.92294 -0.44315  0.05264  0.36653  2.14310 

Random effects:
 Groups   Name        Variance Std.Dev.
 id       (Intercept) 58.00    7.616   
 Residual             14.87    3.857   
Number of obs: 132, groups:  id, 66

Fixed effects:
            Estimate Std. Error       df t value Pr(>|t|)    
(Intercept) -14.4375     1.5091  78.3627  -9.567 8.24e-15 ***
trtE          4.2022     2.1026  78.3627   1.999   0.0491 *  
time8         1.0000     0.9642  64.0000   1.037   0.3036    
trtE:time8    1.0000     1.3434  64.0000   0.744   0.4594    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
           (Intr) trtE   time8 
trtE       -0.718              
time8      -0.319  0.229       
trtE:time8  0.229 -0.319 -0.718
```


:::
:::


위의 적합 결과를 보면 다음과 같은 해석이 가능하다. 먼저 각 요인에 대한 추정치를 살펴보자. 


1. 혈압 강하제의 효과를 보면 기존의 강하제(`C`)를 기준으로 새로운 강하제(`E`)의 효과가 평균적으로 `4.2022` 만큼 크다 (`trtE = 4.2022`). 또한 효과의 차이를 검정하는 경우 p-값은 `p-value = 0.0491` 로 유의수준 $\alpha = 0.05$ 기준으로 유의한 차이를 보인다. 결론은  혈압 강하제 간의 유의한 차이는 있으며 기존의 혈압 강하제(`C`)가 더 효과적이다

2. 혈압 강화제의 시간에 따른 효과의 변화는 `time8 = 1.000` 으로 4주차 변화를 기준으로 8주차에 1 mmHg 만큼 평균적으로 증가하지만(`time8 = 1.0`) 시간에 따른 효과의 차이는 유의하지 않다 (`p-value = 0.3036`).

3. 강하제와 시간 간의 상호작용도 유의하지 않다(`trtE:time8 = 1.0` 그리고 `p-value = 0.4594`)

다음으로 환자의 개인적인 효과를 반영하는 임의효과의 분산이 오차항의 분산의 거의 4배이다.이는 개인 간의 변동이 개인 내의 변동보다 매우 크다는 것을 의미한다. 

$$ \hat \sigma^2_b = 58.00  \quad \hat \sigma^2_e = 14.87$$
반복측정한 자료의 상관계수, 즉 그룹 내의 관측값의  상관계수는 0.7956 으로 매우 높다.

$$ \hat \rho(d_{ij1},d_{ij2}) = \frac{\hat \sigma^2_b }{\hat \sigma^2_b + \hat \sigma^2_2} =\frac{58.0}{58.0 + 14.9} = 0.7956 $$


#### 임의효과가 없는 모형 

만약 반복측정 자료의 구조를 무시하고 개인에 대한 임의효과를 고려하지 않으면 어떻게 될까?임의효과를 모형에 포함하지 않는다면 실험에서 얻은  모든 반응값들이 독립이라는 것이다.

다음과 같이 개인에 대한 임의효과가 없는 모형을 고려하고 적합해 보자.

$$
d_{ijk} = \mu + \alpha_i + \beta_k +  (\alpha\beta)_{ik} + e_{ijk}, \quad i=1,2 ~~ j=1,...,n_i~~ k=1,2
$$ {#eq-re-bloodtrial2} 


::: {.cell}

```{.r .cell-code}
blood_fit1 <- lm(d ~ trt + time + trt*time , data=blood_data1)
summary(blood_fit1)
```

::: {.cell-output .cell-output-stdout}

```

Call:
lm(formula = d ~ trt + time + trt * time, data = blood_data1)

Residuals:
    Min      1Q  Median      3Q     Max 
-17.765  -6.562  -1.562   6.286  23.235 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept)  -14.438      1.509  -9.567   <2e-16 ***
trtE           4.202      2.103   1.999   0.0478 *  
time8          1.000      2.134   0.469   0.6402    
trtE:time8     1.000      2.974   0.336   0.7372    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 8.537 on 128 degrees of freedom
Multiple R-squared:  0.08017,   Adjusted R-squared:  0.05861 
F-statistic: 3.719 on 3 and 128 DF,  p-value: 0.01323
```


:::

```{.r .cell-code}
Anova(blood_fit1, type="III")
```

::: {.cell-output .cell-output-stdout}

```
Anova Table (Type III tests)

Response: d
            Sum Sq  Df F value  Pr(>F)    
(Intercept) 6670.1   1 91.5284 < 2e-16 ***
trt          291.1   1  3.9945 0.04777 *  
time          16.0   1  0.2196 0.64018    
trt:time       8.2   1  0.1131 0.73719    
Residuals   9328.0 128                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
```


:::
:::


혈압 강하제의 효과가 임의효과를 포함한 모형과 같이 유의하게 나타난다. 그런데 여기서 임의효과를 포함 하지 않는 모형의 분석 결과에 유의해야 할 점은 다음과 같다.

- 임의효과를 고려하지 않으면 마치 66명의 두 배인 132 명으로 구성된 독립 표본으로 실험한 것처럼 가정하는 것이다. 따라서 표본의 수가 늘어나는 효과가 생긴다.  

- 반면 임의 효과로 설명되는 그룹의 변동이 오차의 변동에 합쳐지기 때문에 오차항의 분산이 크게 추정된다. 

위의 두 분석 결과를 비교해보면 혼합효과 모형에서 오차항의 분산에 대한 추정치는 $\hat \sigma_e^2 =14.87$ 이지만  임의효과를 고려하지 않은 모형에서는  $\hat \sigma_e^2 =(8.537)^2 = 72.88$ 로 추정된다. 

하지만 임의효과를 고려하지 않은 모형에서는 표본의 수가 늘어나므로, 오차항의 분산이 크게 추정되더라도 추정량에 대한 표준오차(standard error)는 혼합모형과 유사하게 나타난다. 


혼합모형으로 추정한 그룹 내 상관계수($\hat \rho =0.8$)가 매우 크게 나타났으므로 관측값들이 모두 독립이라는 가정은  적절하지 않다. 

각 환자에 대하여 두 반응값을  연결하여 그리면  환자들의 두 반응값들이 매우 가깝게 나타나는 것을 알 수 있다.  


::: {.cell}

```{.r .cell-code}
 ggplot(blood_data1, aes(x=id, y=d, color=trt)) + 
    geom_point()  +
    geom_line() 
```

::: {.cell-output-display}
![](multivar-anova_files/figure-html/unnamed-chunk-10-1.png){width=672}
:::
:::


### 공분산분석

실제로 많은 임상 실험에서는 여러 번 반복 측정을 실시해도 결과를 분석하는 경우 최종 측정값만을 고려한다.
이제 약을 복용하기 전과  8주의 혈압의 차이를 반응변수로 하는 공분산 분석을 실시해 보자. 

약을 복용하기 전과  8주의 혈압의 차이 $d_{ij2} = y_{ij2} - y_{ij0}$ 를 반응변수로 하고 공변량을 실험 전 혈압 $y_{ij0}$으로 하여 분석을 실시한다. 모형은 공분산분석 모형으로 다음과 같다.

$$ d_{ij2} = \mu + \alpha_i + \beta y_{ij0} + e_{ij} $$




::: {.cell}

```{.r .cell-code}
blood_data2 <- blood_data1 %>% filter(time == 8)
head(blood_data2,5)
```

::: {.cell-output .cell-output-stdout}

```
  id trt time bp bp0   d
1  1   C    8 88  95  -7
2  2   C    8 90 100 -10
3  3   C    8 91  98  -7
4  4   C    8 98 114 -16
5  5   C    8 86 110 -24
```


:::
:::


::: {.cell}

```{.r .cell-code}
plot(d ~ trt, data=blood_data2)
```

::: {.cell-output-display}
![](multivar-anova_files/figure-html/unnamed-chunk-12-1.png){width=672}
:::
:::


이제 공분산 모형을 적합해 보자.  처리 간의 차이도 매우 유의하고 실험 전의 혈압도 유의하다. 주목할 점은 
실험 전의 혈압에 대한 회귀계수의 부호가 음수이므로 약을 먹기 전에 혈압이 높을수록 약을 먹은 후의 혈압이 더 많이 감소한다.
이러한 현상은 임상실험에서 자주 나타나는 현상이다. 일반적으로  질병의 정도가 심한 환자일 수록 평균적으로 치료 효과가 더 커진다.  


::: {.cell}

```{.r .cell-code}
blood_ancova <- lm( d ~ trt + bp0, data = blood_data2)
summary(blood_ancova)
```

::: {.cell-output .cell-output-stdout}

```

Call:
lm(formula = d ~ trt + bp0, data = blood_data2)

Residuals:
    Min      1Q  Median      3Q     Max 
-13.982  -6.485  -0.014   5.300  23.505 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)  
(Intercept)  32.8989    21.3060   1.544   0.1276  
trtE          4.6010     1.9778   2.326   0.0232 *
bp0          -0.4486     0.2058  -2.180   0.0330 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.952 on 63 degrees of freedom
Multiple R-squared:  0.1578,    Adjusted R-squared:  0.1311 
F-statistic: 5.903 on 2 and 63 DF,  p-value: 0.004469
```


:::

```{.r .cell-code}
Anova(blood_ancova, type="III")
```

::: {.cell-output .cell-output-stdout}

```
Anova Table (Type III tests)

Response: d
            Sum Sq Df F value  Pr(>F)  
(Intercept)  150.8  1  2.3843 0.12757  
trt          342.2  1  5.4115 0.02323 *
bp0          300.4  1  4.7505 0.03304 *
Residuals   3983.6 63                  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
```


:::
:::



## 분산의 구조 

위의 반복측정자료 예제에서 개체가 3개이고($I=3$) 반복한 시간의 개수가 4번인 경우($J=4$)
각 개체에 대한 임의효과에 대한 계획행렬 $\pmb Z_i$와 전체 계획행렬 $\pmb Z$ 은 다음과 같이 나타난다.

$$  
\pmb Z_i = \pmb Z_* =
\begin{bmatrix}
1 & t_1 \\
1 & t_2 \\
1 & t_3 \\
1 & t_4 
\end{bmatrix}
=
\begin{bmatrix}
1 & 0 \\
1 & 1 \\
1 & 2 \\
1 & 3 
\end{bmatrix}
, ~i=1,2,3 \quad
\pmb Z =
\begin{bmatrix}
\pmb Z_1 & \pmb 0 & \pmb 0 \\
\pmb 0 & \pmb Z_2 & \pmb 0  \\
\pmb 0 &   \pmb 0 & \pmb Z_3  \\
\end{bmatrix}
$$ 
각 개체에 대한 임의효과 벡터 $\pmb b_i$의 분포를  다음과 같이 나타내면

$$  
\pmb b_i =
\begin{bmatrix}
b_{0i} \\
b_{1i} \\
\end{bmatrix} \sim
N \left (
\begin{bmatrix}
0 \\
0 \\
\end{bmatrix}
,
\begin{bmatrix}
\sigma_{b11} &  \sigma_{b12} \\
 \sigma_{b12} & \sigma_{b22}  \\
\end{bmatrix}
\right )
$$ 
위에서 한 개체에 대한 임의효과 벡터 $\pmb b_i$의 공분산을 $\pmb \Psi$라고 하자.

$$ 
 \pmb \Psi = 
 \begin{bmatrix}
\sigma_{b11} &  \sigma_{b12} \\
 \sigma_{b12} & \sigma_{b22}  \\
\end{bmatrix}
$$ 
이제 전체 임의효과 $\pmb b = (\pmb b_1^t,\pmb b_2^t,\pmb b_3^t)^t$의 공분산 행렬 $\pmb G$은 다음과 같다.

$$  
\pmb G = Cov(\pmb b) = 
\begin{bmatrix}
\pmb \Psi & \pmb 0 & \pmb 0\\
\pmb 0 & \pmb \Psi &\pmb 0\\
\pmb 0 & \pmb 0 & \pmb \Psi
\end{bmatrix}
$$ 

따라서  $\pmb Z \pmb G \pmb Z^t$은 다음과 같이 나타난다. 

$$
\begin{aligned}
\pmb Z \pmb G \pmb Z^t
&= 
\begin{bmatrix}
\pmb Z_1 & \pmb 0 & \pmb 0 \\
\pmb 0 & \pmb Z_2 & \pmb 0 \\
\pmb 0 & \pmb 0 & \pmb Z_3 \\
\end{bmatrix}
\begin{bmatrix}
\pmb \Psi & \pmb 0 & \pmb 0\\
\pmb 0 & \pmb \Psi &\pmb 0\\
\pmb 0 & \pmb 0 & \pmb \Psi
\end{bmatrix}
\begin{bmatrix}
\pmb Z_1 & \pmb 0 & \pmb 0 \\
\pmb 0 & \pmb Z_2 & \pmb 0 \\
\pmb 0 & \pmb 0 & \pmb Z_3 \\
\end{bmatrix}^t \\
& =
\begin{bmatrix}
 \pmb Z_1 \pmb \Psi \pmb Z_1^t & \pmb 0 & \pmb 0 \\
\pmb 0 & \pmb Z_2 \pmb \Psi \pmb Z_2^t & \pmb 0 \\
\pmb 0 & \pmb 0 &  \pmb Z_3 \pmb \Psi \pmb Z_3^t\\
\end{bmatrix}
\end{aligned}
$$

이때 $\pmb Z_i \pmb \Psi \pmb Z_i^t= \pmb Z_*  \pmb \Psi\pmb Z_*^t$의 형태는 다음과 같이 모두 같으므로 

$$
\begin{aligned}
\pmb Z_i \pmb \Psi \pmb Z_i^t & =\pmb Z_* \pmb \Psi \pmb Z_*^t \\
& =
\begin{bmatrix}
1 & 0 \\
1 & 1 \\
1 & 2 \\
1 & 3 
\end{bmatrix}
 \begin{bmatrix}
\sigma_{b11} &  \sigma_{b12} \\
 \sigma_{b12} & \sigma_{b22}  \\
\end{bmatrix}
\begin{bmatrix}
1  & 1 & 1 & 1\\
0 & 1 & 2 & 3
\end{bmatrix} \\
& =
\begin{bmatrix}
\sigma_{b11} &  \sigma_{b12}\\
\sigma_{b11} + \sigma_{b12}  & \sigma_{b12} + \sigma_{b22} \\
\sigma_{b11} + 2 \sigma_{b12}  & \sigma_{b12} +  2 \sigma_{b22} \\
\sigma_{b11} + 3 \sigma_{b12}  & \sigma_{b12} + 3 \sigma_{b22} \\
\end{bmatrix} 
\begin{bmatrix}
1  & 1 & 1 & 1\\
0 & 1 & 2 & 3
\end{bmatrix} \\
& =
\begin{bmatrix}
\sigma_{b11} &  \sigma_{b11} + \sigma_{b12} 
   & \sigma_{b11} + 2\sigma_{b12} & \sigma_{b11} + 3\sigma_{b12}\\
\sigma_{b11} + \sigma_{b12}  & \sigma_{b22} + 2\sigma_{b12} + \sigma_{b22}
    &  \sigma_{b22} + 3\sigma_{b12} + 2\sigma_{b22} & \sigma_{b22} + 4\sigma_{b12} + 3\sigma_{b22} \\
\sigma_{b11} + 2\sigma_{b12}  & \sigma_{b22} + 3\sigma_{b12} + 2\sigma_{b22}
    &  \sigma_{b22} + 4\sigma_{b12} + 4\sigma_{b22} & \sigma_{b22} + 5\sigma_{b12} + 6\sigma_{b22} \\
\sigma_{b11} + 3\sigma_{b12}  & \sigma_{b22} + 4\sigma_{b12} + 3\sigma_{b22}
    &  \sigma_{b22} + 5\sigma_{b12} + 6\sigma_{b22} & \sigma_{b22} + 6\sigma_{b12} + 9\sigma_{b22}
\end{bmatrix}
\end{aligned}
$$

관측벡터의 공분산 행렬 $\pmb V=\pmb Z \pmb G \pmb Z^t + \sigma^2_e \pmb I$는 다음과 같이 주어진다.
$$  
\pmb V = diag \{\pmb Z_i \Psi \pmb Z_i^t \}_{i=1}^3 + \sigma^2_e \pmb I_{12}
$$ 

같은 그룹에 속한 관측값의 분산과 공분산은 다음과 같이 직접 계산할 수도 있다.
$$  
 var(y_{ij}) = var((\beta_0 + b_{0i}) + (\beta_1 + b_{1i})t_j + e_{ij})
 = \sigma_{b11} + 2 t_j \sigma_{b12} +  t_j^2 \sigma_{b11} +  \sigma_{e}^2
$$ 
$$
\begin{aligned}
cov(y_{ij}, y_{ik}) & = cov[(\beta_0 + b_{0i}) + (\beta_1 + b_{1i})t_j + e_{ij}, ~
(\beta_0 + b_{0i}) + (\beta_1 + b_{1i})t_k + e_{ik} ] \\
&= cov(b_{0i},b_{0i})) + (t_j +t_k) cov(b_{0i},b_{1i})  + t_j t_k cov(b_{1i},b_{1i})  +
cov(e_{ij} ,e_{ik} ) \\
&= \sigma_{b11} +   (t_j +t_k) \sigma_{b12} +  t_j t_k \sigma_{b11} + 0
\end{aligned}
$$

따라서 같은 그룹에 속한 두 관측값의 상관계수는 다음과  같다.

$$  
cor(y_{ij}, y_{ik}) = 
\frac{\sigma_{b11} +   (t_j +t_k) \sigma_{b12} +  t_j t_k \sigma_{b11} }
{\sqrt{ (\sigma_{b11} + 2 t_j \sigma_{b12} +  t_j^2 \sigma_{b11} +  \sigma_{e}^2)
(\sigma_{b11} + 2 t_k \sigma_{b12} +  t_k^2 \sigma_{b11} +  \sigma_{e}^2)} }
$$ 

--->


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "복사완료!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "복사완료!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation column-page-right">
  <div class="nav-page nav-page-previous">
      <a href="../qmd/multivar-cluster.html" class="pagination-link" aria-label="군집 분석">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">군집 분석</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../references.html" class="pagination-link" aria-label="References">
        <span class="nav-page-text">References</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>